const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Sistema de Información - API',
      version: '1.0.0',
      description: 'API del sistema de información para entrenamiento físico. Gestiona autenticación, perfiles, metabolismo, entrenamientos, dietas, pagos y reportes.',
    },
    servers: [
      { url: 'http://localhost:3000', description: 'Servidor de desarrollo' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Ingresa tu token JWT de acceso en el formato: Bearer <token>',
        },
      },
      responses: {
        Error: {
          description: 'Error controlado por la API',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
            },
          },
        },
        PeticionInvalida: {
          description: 'Petición inválida: los datos de entrada no cumplen las validaciones (Joi). El mensaje corresponde al primer campo inválido.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                campoRequerido: { summary: 'Campo requerido', value: { error: '"nombre" is required' } },
                valorInvalido: { summary: 'Valor inválido', value: { error: '"edad" must be less than or equal to 120' } },
                sinCampos: { summary: 'Sin campos para actualizar', value: { error: 'No se proporcionaron campos para actualizar' } },
              },
            },
          },
        },
        NoAutenticado: {
          description: 'No autenticado: token ausente, invalidado, con tipo incorrecto, expirado o inválido. En login/refresh también incluye credenciales inválidas.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                tokenNoProporcionado: { summary: 'Token no proporcionado', value: { error: 'Token no proporcionado' } },
                tokenInvalidado: { summary: 'Token invalidado (logout)', value: { error: 'Token invalidado' } },
                tokenTipoInvalido: { summary: 'Token con tipo inválido', value: { error: 'Token con tipo inválido' } },
                tokenExpirado: { summary: 'Token expirado', value: { error: 'Token expirado' } },
                tokenInvalido: { summary: 'Token inválido', value: { error: 'Token inválido' } },
                credencialesInvalidas: { summary: 'Credenciales inválidas (login)', value: { error: 'La contraseña es incorrecta' } },
              },
            },
          },
        },
        AccesoDenegado: {
          description: 'El rol del usuario autenticado no tiene permiso para este recurso.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                rolSinPermiso: { summary: 'Rol sin permiso', value: { error: 'Acceso denegado para este rol' } },
                noPropietario: { summary: 'Recurso de otro usuario', value: { error: 'No estás asignado a este entrenador' } },
              },
            },
          },
        },
        NoEncontrado: {
          description: 'El recurso solicitado no existe (o el usuario no tiene acceso a él).',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { error: 'Recurso no encontrado' },
            },
          },
        },
        Conflicto: {
          description: 'Conflicto con el estado actual del recurso (registro duplicado, pago ya procesado, bloqueo del Guardian).',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                emailDuplicado: { summary: 'Email duplicado', value: { error: 'El email ya está registrado' } },
                pagoProcesado: { summary: 'Pago ya procesado', value: { error: 'El pago ya fue procesado (estado actual: verificado)' } },
              },
            },
          },
        },
        DemasiadasSolicitudes: {
          description: 'Límite de peticiones excedido (rate limiting). Ventanas: login 20/15min, registro 10/h, refresh 30/15min.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                login: { summary: 'Login', value: { error: 'Demasiados intentos. Intenta de nuevo en 15 minutos.' } },
                registro: { summary: 'Registro', value: { error: 'Demasiados registros desde esta IP. Intenta de nuevo en 1 hora.' } },
                refresh: { summary: 'Refresh', value: { error: 'Demasiadas solicitudes de renovación. Intenta de nuevo en 15 minutos.' } },
              },
            },
          },
        },
        ErrorServidor: {
          description: 'Error interno del servidor. En producción no se expone el detalle del error.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { error: 'Error interno del servidor' },
            },
          },
        },
        SinContenido: {
          description: 'Recurso procesado correctamente. La respuesta no incluye cuerpo.',
        },
        IaRespuestaInvalida: {
          description: 'El servicio de IA respondió con un formato inesperado o inválido. El campo data incluye la respuesta recibida.',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  error: { type: 'string' },
                  data: { type: 'object', nullable: true },
                },
              },
              example: { error: 'Respuesta inválida del servicio de IA', data: { success: true } },
            },
          },
        },
        IaNoDisponible: {
          description: 'El servicio de IA (Flask) no está disponible o rechazó la conexión.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { error: 'Servicio de IA no disponible' },
            },
          },
        },
        IaTimeout: {
          description: 'Tiempo de espera agotado al contactar el servicio de IA (Flask).',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { error: 'Timeout al conectar con servicio de IA' },
            },
          },
        },
      },
      schemas: {
        ErrorResponse: {
          type: 'object',
          properties: {
            error: { type: 'string', description: 'Mensaje descriptivo del error' },
          },
          example: { error: 'Mensaje de error descriptivo' },
        },
        AuthSuccessResponse: {
          type: 'object',
          properties: {
            accessToken: { type: 'string', description: 'JWT de acceso (15 min de validez)' },
            refreshToken: { type: 'string', description: 'JWT de actualización (10 días de validez)' },
            user: {
              type: 'object',
              properties: {
                id: { type: 'integer', description: 'ID del usuario' },
                nombre: { type: 'string', description: 'Nombre completo' },
                email: { type: 'string', format: 'email', description: 'Correo electrónico' },
                rol: { type: 'string', enum: ['administrador', 'entrenador', 'instruido'], description: 'Rol del usuario' },
                tipo: { type: 'string', enum: ['entrenador', 'instruido'], description: 'Tipo de cuenta' },
                especialidad: { type: 'string', nullable: true, description: 'Especialidad (solo entrenadores/administradores)' },
                perfilMedicoCompleto: {
                  type: 'boolean',
                  nullable: true,
                  description: 'Solo para rol instruido (login/registro): indica si ya completó su perfil médico',
                },
              },
            },
          },
          example: {
            accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            user: {
              id: 1,
              nombre: 'Juan Pérez',
              email: 'juan@example.com',
              rol: 'entrenador',
              tipo: 'entrenador',
              especialidad: 'Nutrición deportiva',
            },
          },
        },
        TokenPairResponse: {
          type: 'object',
          properties: {
            accessToken: { type: 'string', description: 'Nuevo JWT de acceso' },
            refreshToken: { type: 'string', description: 'Nuevo JWT de actualización' },
          },
          example: {
            accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
          },
        },
        LogoutResponse: {
          type: 'object',
          properties: {
            message: { type: 'string', description: 'Mensaje de confirmación' },
          },
          example: { message: 'Sesión cerrada correctamente' },
        },
        UserEntrenador: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            email: { type: 'string', format: 'email' },
            especialidad: { type: 'string', nullable: true },
            rol: { type: 'string', enum: ['administrador', 'entrenador'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            nombre: 'Carlos López',
            email: 'carlos@example.com',
            especialidad: 'Entrenamiento funcional',
            rol: 'entrenador',
            createdAt: '2025-01-15T10:30:00.000Z',
            updatedAt: '2025-06-20T14:22:00.000Z',
          },
        },
        UserInstruido: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            email: { type: 'string', format: 'email' },
            edad: { type: 'integer' },
            peso: { type: 'number', format: 'decimal' },
            altura: { type: 'number', format: 'decimal' },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            nivelExperiencia: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            propositoEntrenamiento: { type: 'string', nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7 },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minimum: 1, maximum: 7 },
            fechaRegistro: { type: 'string', format: 'date' },
            activo: { type: 'boolean' },
            entrenadorId: { type: 'integer', nullable: true },
            rol: { type: 'string' },
            perfilMedicoCompleto: { type: 'boolean', description: 'Solo en /api/auth/me y login: indica si el perfil médico está completo' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 2,
            nombre: 'María García',
            email: 'maria@example.com',
            edad: 28,
            peso: 65.50,
            altura: 1.65,
            sexo: 'femenino',
            nivelActividad: 'activo',
            propositoEntrenamiento: 'Perder peso y tonificar',
            diasDisponibles: 4,
            diasSemana: [1, 3, 5, 6],
            fechaRegistro: '2025-03-10',
            activo: true,
            entrenadorId: 1,
            rol: 'instruido',
            createdAt: '2025-03-10T09:00:00.000Z',
            updatedAt: '2025-07-01T16:45:00.000Z',
          },
        },
        RegisterRequest: {
          type: 'object',
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100 },
            contrasena: { type: 'string', minLength: 8, maxLength: 100, description: 'Contraseña del usuario' },
            especialidad: { type: 'string', maxLength: 100, nullable: true },
            rol: { type: 'string', enum: ['administrador', 'entrenador', 'instruido'], default: 'instruido' },
            edad: { type: 'integer', minimum: 1, maximum: 120, description: 'Requerido si rol=instruido' },
            peso: { type: 'number', exclusiveMinimum: 0, description: 'Requerido si rol=instruido' },
            altura: { type: 'number', exclusiveMinimum: 0, description: 'Requerido si rol=instruido' },
            sexo: { type: 'string', enum: ['masculino', 'femenino'], description: 'Requerido si rol=instruido' },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'], description: 'Requerido si rol=instruido' },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7, description: 'Requerido si rol=instruido' },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minimum: 1, maximum: 7, description: 'Requerido si rol=instruido' },
            entrenadorId: { type: 'integer', nullable: true },
          },
          example: {
            nombre: 'Nuevo Usuario',
            email: 'nuevo@example.com',
            contrasena: 'Password123',
            rol: 'entrenador',
            especialidad: 'Yoga y meditación',
          },
        },
        RegisterInstruidoRequest: {
          type: 'object',
          required: ['nombre', 'email', 'contrasena', 'edad', 'peso', 'altura', 'sexo', 'nivelActividad', 'diasDisponibles', 'diasSemana'],
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100 },
            contrasena: { type: 'string', minLength: 8, maxLength: 100 },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            peso: { type: 'number', exclusiveMinimum: 0 },
            altura: { type: 'number', exclusiveMinimum: 0 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            propositoEntrenamiento: { type: 'string', nullable: true },
            nivelExperiencia: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7 },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minimum: 1, maximum: 7 },
          },
          example: {
            nombre: 'Ana Martínez',
            email: 'ana@example.com',
            contrasena: 'MiClaveSegura1',
            edad: 25,
            peso: 58.0,
            altura: 1.62,
            sexo: 'femenino',
            nivelActividad: 'moderado',
            propositoEntrenamiento: 'Mejorar condición física general',
            nivelExperiencia: 'intermedio',
            diasDisponibles: 3,
            diasSemana: [1, 3, 5],
          },
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'contrasena'],
          properties: {
            email: { type: 'string', format: 'email' },
            contrasena: { type: 'string', description: 'Contraseña del usuario' },
          },
          example: {
            email: 'usuario@example.com',
            contrasena: 'MiPassword123',
          },
        },
        RefreshRequest: {
          type: 'object',
          required: ['refreshToken'],
          properties: {
            refreshToken: { type: 'string', description: 'JWT de actualización' },
          },
          example: {
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
          },
        },
        UpdateProfileRequest: {
          type: 'object',
          properties: {
            nombre: { type: 'string', maxLength: 100, nullable: true },
            email: { type: 'string', format: 'email', maxLength: 100, nullable: true },
            especialidad: { type: 'string', maxLength: 100, nullable: true, description: 'Solo para entrenadores' },
            contrasena: { type: 'string', minLength: 8, maxLength: 100, nullable: true, description: 'Nueva contraseña' },
            contrasenaActual: { type: 'string', description: 'Obligatorio si se proporciona contrasena' },
            edad: { type: 'integer', minimum: 1, maximum: 120, nullable: true },
            peso: { type: 'number', exclusiveMinimum: 0, nullable: true },
            altura: { type: 'number', exclusiveMinimum: 0, nullable: true },
            sexo: { type: 'string', enum: ['masculino', 'femenino'], nullable: true },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'], nullable: true },
            propositoEntrenamiento: { type: 'string', nullable: true },
            nivelExperiencia: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7, nullable: true },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minimum: 1, maximum: 7, nullable: true },
          },
          example: {
            nombre: 'Nombre Actualizado',
            especialidad: 'Nueva especialidad',
            diasDisponibles: 4,
            diasSemana: [1, 3, 5, 6],
          },
        },
        HealthResponse: {
          type: 'object',
          properties: {
            status: { type: 'string' },
            service: { type: 'string' },
          },
          example: { status: 'ok', service: 'backend-node' },
        },
        Certificacion: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            institucion: { type: 'string', nullable: true },
            fechaObtencion: { type: 'string', format: 'date', nullable: true },
            fechaExpiracion: { type: 'string', format: 'date', nullable: true },
            descripcion: { type: 'string', nullable: true },
            imagenUrl: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            nombre: 'CrossFit Level 2 Trainer',
            institucion: 'CrossFit Inc.',
            fechaObtencion: '2024-01-15',
            fechaExpiracion: '2026-01-15',
            descripcion: 'Certificación avanzada en entrenamiento funcional',
            imagenUrl: 'https://ejemplo.com/cert-crossfit-l2.jpg',
          },
        },
        CertificacionRequest: {
          type: 'object',
          required: ['nombre'],
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            institucion: { type: 'string', maxLength: 150, nullable: true },
            fechaObtencion: { type: 'string', format: 'date', nullable: true },
            fechaExpiracion: { type: 'string', format: 'date', nullable: true },
            descripcion: { type: 'string', nullable: true },
            imagenUrl: { type: 'string', format: 'uri', nullable: true },
          },
          example: {
            nombre: 'Certificación en Nutrición Deportiva',
            institucion: 'Universidad Nacional',
            fechaObtencion: '2023-06-01',
            fechaExpiracion: '2028-06-01',
            descripcion: 'Especialización en nutrición para deportistas',
            imagenUrl: 'https://ejemplo.com/cert-nutricion.jpg',
          },
        },
        EjercicioResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            descripcion: { type: 'string', nullable: true },
            instruccionesEs: { type: 'string', nullable: true },
            grupoMuscular: { type: 'string', nullable: true },
            target: { type: 'string', nullable: true },
            equipoNecesario: { type: 'string', nullable: true },
            dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            musculosSecundarios: { type: 'array', items: { type: 'string' }, nullable: true },
            contraindicaLesiones: { type: 'string', nullable: true },
            imagenUrl: { type: 'string', nullable: true },
            gifUrl: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            nombre: 'Sentadilla con barra',
            descripcion: 'Ejercicio compuesto para tren inferior',
            instruccionesEs: 'Colocar la barra sobre trapecios, bajar hasta parallelo y subir.',
            grupoMuscular: 'Cuádriceps',
            target: 'Piernas',
            equipoNecesario: 'Barra, rack',
            dificultad: 'intermedio',
            musculosSecundarios: ['Glúteos', 'Isquiotibiales'],
            contraindicaLesiones: 'Rodilla, espalda baja',
            imagenUrl: 'https://ejemplo.com/sentadilla.jpg',
            gifUrl: 'https://ejemplo.com/sentadilla.gif',
          },
        },
        EjercicioListResponse: {
          type: 'object',
          description: 'Cuando se aplica al menos un filtro o paginación se devuelve este objeto paginado; sin filtros se devuelve un array plano de ejercicios.',
          properties: {
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioResponse' } },
            total: { type: 'integer' },
            pagina: { type: 'integer' },
            limite: { type: 'integer', description: 'Entre 1 y 100 (default 50)' },
            totalPaginas: { type: 'integer' },
          },
          example: {
            ejercicios: [
              { id: 1, nombre: 'Sentadilla con barra', grupoMuscular: 'Cuádriceps', dificultad: 'intermedio' },
              { id: 2, nombre: 'Press de banca', grupoMuscular: 'Pecho', dificultad: 'intermedio' },
            ],
            total: 150,
            pagina: 1,
            limite: 50,
            totalPaginas: 3,
          },
        },
        EjercicioCreateRequest: {
          type: 'object',
          required: ['nombre'],
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string' },
            instruccionesEs: { type: 'string' },
            grupoMuscular: { type: 'string', maxLength: 50 },
            target: { type: 'string', maxLength: 100 },
            equipoNecesario: { type: 'string', maxLength: 100 },
            dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
            musculosSecundarios: { type: 'array', items: { type: 'string' } },
            contraindicaLesiones: { type: 'string' },
            imagenUrl: { type: 'string' },
            gifUrl: { type: 'string' },
          },
          example: {
            nombre: 'Remo con mancuerna',
            descripcion: 'Ejercicio unilateral para espalda',
            grupoMuscular: 'Espalda',
            target: 'Dorsal',
            equipoNecesario: 'Mancuerna',
            dificultad: 'principiante',
          },
        },
        EjercicioUpdateRequest: {
          type: 'object',
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string' },
            instruccionesEs: { type: 'string' },
            grupoMuscular: { type: 'string', maxLength: 50 },
            target: { type: 'string', maxLength: 100 },
            equipoNecesario: { type: 'string', maxLength: 100 },
            dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
            musculosSecundarios: { type: 'array', items: { type: 'string' } },
            contraindicaLesiones: { type: 'string' },
            imagenUrl: { type: 'string' },
            gifUrl: { type: 'string' },
          },
          example: {
            nombre: 'Sentadilla con barra (actualizado)',
            dificultad: 'avanzado',
          },
        },
        EjercicioRutinaItem: {
          type: 'object',
          description: 'Elemento de ejercicio dentro de una plantilla o rutina asignada (JSON almacenado en camelCase).',
          properties: {
            ejercicioId: { type: 'integer', description: 'ID del ejercicio del catálogo' },
            nombre: { type: 'string', description: 'Nombre del ejercicio (resuelto del catálogo, solo en endpoints de día)' },
            dia: { type: 'integer', minimum: 1, maximum: 7, description: 'Día de la semana (1-7)' },
            orden: { type: 'integer', minimum: 1, description: 'Orden dentro del día' },
            series: { type: 'integer', minimum: 1, maximum: 20 },
            repeticiones: { type: 'integer', minimum: 1, maximum: 100 },
            cargaKg: { type: 'number', minimum: 0, nullable: true },
            descansoSegundos: { type: 'integer', minimum: 0, maximum: 600 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            ejercicioId: 1,
            nombre: 'Sentadilla con barra',
            dia: 1,
            orden: 1,
            series: 4,
            repeticiones: 8,
            cargaKg: 60,
            descansoSegundos: 90,
            notas: 'Controlar la bajada',
          },
        },
        PlantillaResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            descripcion: { type: 'string', nullable: true },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
            diasSemana: { type: 'object', description: 'Mapa de días de la semana' },
            frecuenciaSemanal: { type: 'integer' },
            duracionSemanas: { type: 'integer', nullable: true },
            objetivo: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'], nullable: true },
            nivelDificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            activa: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            nombre: 'Full Body Fuerza',
            descripcion: 'Rutina de fuerza tren completo 3 días',
            tipo: 'fuerza',
            ejercicios: [
              { ejercicioId: 1, dia: 1, orden: 1, series: 4, repeticiones: 8, cargaKg: 60, descansoSegundos: 90 },
              { ejercicioId: 5, dia: 1, orden: 2, series: 3, repeticiones: 10, cargaKg: 30, descansoSegundos: 60 },
            ],
            diasSemana: { '1': { diaSemana: 1, nombre: 'Lunes' }, '3': { diaSemana: 3, nombre: 'Miércoles' }, '5': { diaSemana: 5, nombre: 'Viernes' } },
            frecuenciaSemanal: 3,
            duracionSemanas: 8,
            objetivo: 'ganancia_muscular',
            nivelDificultad: 'intermedio',
            activa: true,
            createdAt: '2025-06-01T10:00:00.000Z',
            updatedAt: '2025-07-01T10:00:00.000Z',
          },
        },
        PlantillaCreateRequest: {
          type: 'object',
          required: ['nombre', 'tipo', 'ejercicios', 'diasSemana', 'frecuenciaSemanal'],
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string', maxLength: 2000, nullable: true },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' }, minItems: 1 },
            diasSemana: { type: 'object', description: 'Mapa { "1": { diaSemana: 1, nombre: "Lunes" } }, claves "1"-"7"' },
            frecuenciaSemanal: { type: 'integer', minimum: 1, maximum: 7 },
            duracionSemanas: { type: 'integer', minimum: 1, maximum: 52 },
            objetivo: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'] },
            nivelDificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
          },
          example: {
            nombre: 'Push Pull Legs',
            descripcion: 'Rutina de hipertrofia torso-pierna',
            tipo: 'hipertrofia',
            ejercicios: [
              { ejercicioId: 2, dia: 1, orden: 1, series: 4, repeticiones: 10, cargaKg: 40, descansoSegundos: 90 },
              { ejercicioId: 7, dia: 1, orden: 2, series: 3, repeticiones: 12, cargaKg: 15, descansoSegundos: 60 },
            ],
            diasSemana: { '1': { diaSemana: 1, nombre: 'Lunes' }, '3': { diaSemana: 3, nombre: 'Miércoles' }, '5': { diaSemana: 5, nombre: 'Viernes' } },
            frecuenciaSemanal: 3,
            duracionSemanas: 12,
            objetivo: 'ganancia_muscular',
            nivelDificultad: 'intermedio',
          },
        },
        PlantillaUpdateRequest: {
          type: 'object',
          description: 'Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string', maxLength: 2000, nullable: true },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' }, minItems: 1 },
            diasSemana: { type: 'object', description: 'Mapa { "1": { diaSemana: 1, nombre: "Lunes" } }' },
            frecuenciaSemanal: { type: 'integer', minimum: 1, maximum: 7 },
            duracionSemanas: { type: 'integer', minimum: 1, maximum: 52 },
            objetivo: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'] },
            nivelDificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
            activa: { type: 'boolean' },
          },
          example: {
            nombre: 'Push Pull Legs (v2)',
            activa: false,
          },
        },
        AgregarEjercicioDiaRequest: {
          type: 'object',
          required: ['ejercicioId', 'series', 'repeticiones'],
          properties: {
            ejercicioId: { type: 'integer' },
            orden: { type: 'integer', minimum: 1, description: 'Si se omite se agrega al final del día' },
            series: { type: 'integer', minimum: 1, maximum: 20 },
            repeticiones: { type: 'integer', minimum: 1, maximum: 100 },
            cargaKg: { type: 'number', minimum: 0, nullable: true },
            descansoSegundos: { type: 'integer', minimum: 0, maximum: 600 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            ejercicioId: 3,
            series: 3,
            repeticiones: 12,
            cargaKg: 20,
            descansoSegundos: 60,
            notas: 'Pecho inclinado con mancuernas',
          },
        },
        EditarEjercicioDiaRequest: {
          type: 'object',
          description: 'Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            ejercicioId: { type: 'integer' },
            series: { type: 'integer', minimum: 1, maximum: 20 },
            repeticiones: { type: 'integer', minimum: 1, maximum: 100 },
            cargaKg: { type: 'number', minimum: 0, nullable: true },
            descansoSegundos: { type: 'integer', minimum: 0, maximum: 600 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            series: 4,
            repeticiones: 8,
            cargaKg: 62.5,
          },
        },
        ReordenarRequest: {
          type: 'object',
          required: ['orden'],
          properties: {
            orden: {
              type: 'array',
              items: { type: 'integer', minimum: 0 },
              minItems: 1,
              description: 'Nuevo orden de los índices actuales de los ejercicios del día; debe contener todos',
            },
          },
          example: { orden: [2, 0, 1] },
        },
        EjercicioEliminadoResponse: {
          type: 'object',
          properties: {
            eliminado: { type: 'boolean', example: true },
            ejercicio: { $ref: '#/components/schemas/EjercicioRutinaItem' },
          },
          example: {
            eliminado: true,
            ejercicio: { ejercicioId: 5, nombre: 'Press inclinado', dia: 1, orden: 2, series: 3, repeticiones: 10, cargaKg: 30, descansoSegundos: 60 },
          },
        },
        PlantillaDiaResponse: {
          type: 'object',
          properties: {
            plantillaId: { type: 'integer' },
            nombre: { type: 'string', description: 'Nombre de la plantilla' },
            dia: { type: 'integer', minimum: 1, maximum: 7 },
            configuracionDia: {
              type: 'object',
              nullable: true,
              properties: {
                diaSemana: { type: 'integer', minimum: 1, maximum: 7 },
                nombre: { type: 'string' },
              },
              description: 'Configuración del día declarada en diasSemana; null si el día no está configurado',
            },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
          },
          example: {
            plantillaId: 1,
            nombre: 'Full Body Fuerza',
            dia: 1,
            configuracionDia: { diaSemana: 1, nombre: 'Lunes' },
            ejercicios: [
              { ejercicioId: 1, nombre: 'Sentadilla con barra', dia: 1, orden: 1, series: 4, repeticiones: 8, cargaKg: 60, descansoSegundos: 90 },
              { ejercicioId: 5, nombre: 'Press de banca', dia: 1, orden: 2, series: 3, repeticiones: 10, cargaKg: 30, descansoSegundos: 60 },
            ],
          },
        },
        RutinaAsignadaResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            plantillaOrigenId: { type: 'integer', nullable: true },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
            diasSemana: { type: 'object', description: 'Mapa { "1": { diaSemana, nombre } }' },
            frecuenciaSemanal: { type: 'integer' },
            duracionSemanas: { type: 'integer', nullable: true },
            observaciones: { type: 'string', nullable: true },
            personalizadaPorEntrenador: { type: 'boolean' },
            decision: { type: 'string', enum: ['pendiente', 'aprobada', 'rechazada'], description: 'Estado del flujo HITL' },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            activa: { type: 'boolean' },
            eliminado: { type: 'boolean', description: 'Borrado lógico' },
            Instruido: {
              type: 'object',
              nullable: true,
              description: 'Incluido solo en el listado GET /api/entrenamiento/asignadas',
              properties: {
                id: { type: 'integer' },
                nombre: { type: 'string' },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            instruidoId: 2,
            plantillaOrigenId: 1,
            entrenadorId: 1,
            nombre: 'IA - Full Body Fuerza',
            tipo: 'fuerza',
            ejercicios: [
              { ejercicioId: 1, nombre: 'Sentadilla con barra', dia: 1, orden: 1, series: 4, repeticiones: 8, cargaKg: 50, descansoSegundos: 90 },
            ],
            diasSemana: { '1': { diaSemana: 1, nombre: 'Lunes' }, '3': { diaSemana: 3, nombre: 'Miércoles' } },
            frecuenciaSemanal: 2,
            duracionSemanas: 6,
            observaciones: '{"confianza":0.85,"explicacion":"Basado en nivel intermedio"}',
            personalizadaPorEntrenador: false,
            decision: 'aprobada',
            fechaInicio: '2025-07-01',
            fechaFin: '2025-08-12',
            activa: true,
            eliminado: false,
            Instruido: { id: 2, nombre: 'Ana Martínez' },
            createdAt: '2025-07-01T09:00:00.000Z',
            updatedAt: '2025-07-01T09:30:00.000Z',
          },
        },
        RutinaCreateRequest: {
          type: 'object',
          required: ['instruidoId', 'nombre', 'tipo'],
          properties: {
            instruidoId: { type: 'integer' },
            plantillaOrigenId: { type: 'integer', nullable: true },
            nombre: { type: 'string', maxLength: 150 },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' }, default: [] },
            diasSemana: { type: 'object', description: 'Mapa { "1": { diaSemana, nombre } }, default {}' },
            frecuenciaSemanal: { type: 'integer', minimum: 1, maximum: 7, default: 3 },
            duracionSemanas: { type: 'integer', minimum: 1, maximum: 52 },
            observaciones: { type: 'string', nullable: true },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
          },
          example: {
            instruidoId: 2,
            nombre: 'Rutina Personal Ana',
            tipo: 'hipertrofia',
            ejercicios: [
              { ejercicioId: 1, dia: 1, orden: 1, series: 4, repeticiones: 10, cargaKg: 40, descansoSegundos: 90 },
            ],
            diasSemana: { '1': { diaSemana: 1, nombre: 'Lunes' }, '4': { diaSemana: 4, nombre: 'Jueves' } },
            frecuenciaSemanal: 2,
            duracionSemanas: 8,
            fechaInicio: '2025-07-01',
          },
        },
        RutinaUpdateRequest: {
          type: 'object',
          description: 'Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' }, minItems: 1 },
            diasSemana: { type: 'object' },
            frecuenciaSemanal: { type: 'integer', minimum: 1, maximum: 7 },
            duracionSemanas: { type: 'integer', minimum: 1, maximum: 52 },
            observaciones: { type: 'string', nullable: true },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            activa: { type: 'boolean' },
          },
          example: {
            frecuenciaSemanal: 3,
            activa: false,
          },
        },
        RutinaClonarRequest: {
          type: 'object',
          required: ['instruidoId'],
          properties: {
            instruidoId: { type: 'integer' },
            fechaInicio: { type: 'string', format: 'date' },
            observaciones: { type: 'string', nullable: true },
          },
          example: {
            instruidoId: 6,
            fechaInicio: '2025-07-15',
            observaciones: 'Clonada desde plantilla para nuevo cliente',
          },
        },
        RutinaDiaResponse: {
          type: 'object',
          properties: {
            rutinaId: { type: 'integer' },
            nombre: { type: 'string', description: 'Nombre de la rutina' },
            dia: { type: 'integer', minimum: 1, maximum: 7 },
            configuracionDia: {
              type: 'object',
              nullable: true,
              properties: {
                diaSemana: { type: 'integer', minimum: 1, maximum: 7 },
                nombre: { type: 'string' },
              },
            },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
          },
          example: {
            rutinaId: 1,
            nombre: 'IA - Full Body Fuerza',
            dia: 1,
            configuracionDia: { diaSemana: 1, nombre: 'Lunes' },
            ejercicios: [
              { ejercicioId: 1, nombre: 'Sentadilla con barra', dia: 1, orden: 1, series: 4, repeticiones: 8, cargaKg: 50, descansoSegundos: 90 },
            ],
          },
        },
        RutinaResumenResponse: {
          type: 'object',
          properties: {
            rutinaId: { type: 'integer' },
            nombre: { type: 'string' },
            tipo: { type: 'string' },
            frecuenciaSemanal: { type: 'integer' },
            totalEjercicios: { type: 'integer' },
            configuracionDias: { type: 'object', description: 'Mapa de días configurados en la rutina' },
            dias: {
              type: 'object',
              description: 'Mapa {"1"-"7": { diaSemana, nombre, totalEjercicios, ejercicios[] }} de los días con configuración',
            },
          },
          example: {
            rutinaId: 1,
            nombre: 'IA - Full Body Fuerza',
            tipo: 'fuerza',
            frecuenciaSemanal: 3,
            totalEjercicios: 12,
            configuracionDias: { '1': { diaSemana: 1, nombre: 'Lunes' }, '3': { diaSemana: 3, nombre: 'Miércoles' }, '5': { diaSemana: 5, nombre: 'Viernes' } },
            dias: {
              '1': { diaSemana: 1, nombre: 'Lunes', totalEjercicios: 4, ejercicios: [{ ejercicioId: 1, nombre: 'Sentadilla con barra', dia: 1, orden: 1, series: 4, repeticiones: 8, cargaKg: 50 }] },
              '3': { diaSemana: 3, nombre: 'Miércoles', totalEjercicios: 4, ejercicios: [] },
              '5': { diaSemana: 5, nombre: 'Viernes', totalEjercicios: 4, ejercicios: [] },
            },
          },
        },
        RegistroEntrenamientoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            rutinaAsignadaId: { type: 'integer' },
            instruidoId: { type: 'integer' },
            fecha: { type: 'string', format: 'date' },
            ejerciciosRealizados: { type: 'array', items: { type: 'object' }, nullable: true },
            duracionMinutos: { type: 'integer', nullable: true },
            percepcionEsfuerzo: { type: 'integer', minimum: 1, maximum: 10, nullable: true },
            observaciones: { type: 'string', nullable: true },
            estado: { type: 'string', enum: ['en_progreso', 'completado', 'cancelado'] },
            fechaInicio: { type: 'string', format: 'date-time' },
            fechaFin: { type: 'string', format: 'date-time', nullable: true },
          },
          example: {
            id: 1,
            rutinaAsignadaId: 1,
            instruidoId: 2,
            fecha: '2025-07-10',
            ejerciciosRealizados: [
              { ejercicio_id: 1, nombre: 'Sentadilla', series_completadas: 4 },
            ],
            duracionMinutos: 55,
            percepcionEsfuerzo: 7,
            observaciones: 'Buena sesión',
            estado: 'completado',
            fechaInicio: '2025-07-10T08:00:00.000Z',
            fechaFin: '2025-07-10T08:55:00.000Z',
          },
        },
        RegistroCrearRequest: {
          type: 'object',
          required: ['rutinaAsignadaId'],
          properties: {
            rutinaAsignadaId: { type: 'integer' },
            instruidoId: { type: 'integer' },
            fecha: { type: 'string', format: 'date' },
            ejerciciosRealizados: { type: 'array', items: { type: 'object' } },
            percepcionEsfuerzo: { type: 'integer', minimum: 1, maximum: 10 },
            duracionMinutos: { type: 'integer', minimum: 0, maximum: 600 },
            observaciones: { type: 'string', maxLength: 2000 },
          },
          example: {
            rutinaAsignadaId: 1,
            fecha: '2025-07-10',
            percepcionEsfuerzo: 7,
            duracionMinutos: 55,
            observaciones: 'Buena sesión de fuerza',
          },
        },
        RegistroIniciarRequest: {
          type: 'object',
          required: ['rutinaAsignadaId'],
          properties: {
            rutinaAsignadaId: { type: 'integer' },
            instruidoId: { type: 'integer' },
            observaciones: { type: 'string', maxLength: 2000 },
          },
          example: {
            rutinaAsignadaId: 1,
            observaciones: 'Inicio de sesión de entrenamiento',
          },
        },
        SerieResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            registroEntrenamientoId: { type: 'integer' },
            ejercicioId: { type: 'integer' },
            numeroSerie: { type: 'integer' },
            repeticionesRealizadas: { type: 'integer' },
            pesoKg: { type: 'number' },
            descansoSegundos: { type: 'integer' },
            rpe: { type: 'integer', minimum: 1, maximum: 10, nullable: true },
            notas: { type: 'string', nullable: true },
            ejercicio: {
              type: 'object',
              nullable: true,
              description: 'Datos del catálogo; incluido solo en GET /api/entrenamiento/registro/{id} y GET /api/entrenamiento/registro/{id}/series',
              properties: {
                id: { type: 'integer' },
                nombre: { type: 'string' },
                grupoMuscular: { type: 'string', nullable: true },
              },
            },
          },
          example: {
            id: 1,
            registroEntrenamientoId: 1,
            ejercicioId: 1,
            numeroSerie: 1,
            repeticionesRealizadas: 8,
            pesoKg: 60,
            descansoSegundos: 90,
            rpe: 7,
            notas: null,
            ejercicio: { id: 1, nombre: 'Sentadilla con barra', grupoMuscular: 'Cuádriceps' },
          },
        },
        SerieCreateRequest: {
          type: 'object',
          required: ['ejercicioId', 'numeroSerie', 'repeticionesRealizadas', 'pesoKg', 'descansoSegundos'],
          properties: {
            ejercicioId: { type: 'integer' },
            numeroSerie: { type: 'integer', minimum: 1 },
            repeticionesRealizadas: { type: 'integer', minimum: 0 },
            pesoKg: { type: 'number', minimum: 0 },
            descansoSegundos: { type: 'integer', minimum: 0 },
            rpe: { type: 'integer', minimum: 1, maximum: 10 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            ejercicioId: 1,
            numeroSerie: 1,
            repeticionesRealizadas: 8,
            pesoKg: 60,
            descansoSegundos: 90,
            rpe: 7,
          },
        },
        SerieUpdateRequest: {
          type: 'object',
          properties: {
            ejercicioId: { type: 'integer' },
            numeroSerie: { type: 'integer', minimum: 1 },
            repeticionesRealizadas: { type: 'integer', minimum: 0 },
            pesoKg: { type: 'number', minimum: 0 },
            descansoSegundos: { type: 'integer', minimum: 0 },
            rpe: { type: 'integer', minimum: 1, maximum: 10 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            repeticionesRealizadas: 10,
            pesoKg: 62.5,
          },
        },
        HITLSugerenciaRutinaRequest: {
          type: 'object',
          properties: {
            preferencias: {
              type: 'object',
              properties: {
                excluir: { type: 'array', items: { type: 'string' }, description: 'IDs o nombres de ejercicios a excluir' },
                equipamiento: { type: 'array', items: { type: 'string' }, description: 'Equipamiento disponible' },
              },
            },
          },
          example: {
            preferencias: {
              excluir: ['Sentadilla con barra'],
              equipamiento: ['Mancuernas', 'Barra', 'Banco'],
            },
          },
        },
        HITLSugerenciaRutinaResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            plantillaId: { type: 'integer', nullable: true, description: 'ID de la plantilla sugerida por la IA' },
            confianza: { type: 'number', minimum: 0, maximum: 1, description: 'Nivel de confianza del modelo (0-1)' },
            explicacion: { type: 'string', nullable: true, description: 'Justificación de la recomendación' },
            advertencia: { type: 'string', nullable: true, description: 'Advertencia de seguridad si aplica' },
            hasLesiones: { type: 'boolean', description: 'Si el cliente tiene lesiones registradas' },
            sinLesiones: { type: 'boolean', nullable: true, description: 'True si no hay lesiones ni condiciones, false si las hay, null si no se pudo determinar' },
            metadata: { type: 'object', description: 'Metadatos adicionales del modelo' },
          },
          example: {
            success: true,
            plantillaId: 3,
            confianza: 0.87,
            explicacion: 'Se recomienda rutina de hipertrofia moderada dado nivel intermedio y disponibilidad de 4 días.',
            advertencia: null,
            hasLesiones: true,
            sinLesiones: false,
            metadata: { modelo: 'recommender_v2', tiempoMs: 320 },
          },
        },
        HITLDecisionRutinaRequest: {
          type: 'object',
          properties: {
            accion: { type: 'string', enum: ['aceptada', 'modificada', 'rechazada'], description: 'Decisión del entrenador' },
            comentario: { type: 'string', nullable: true, description: 'Comentario opcional' },
            nombre: { type: 'string', nullable: true },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'], nullable: true },
            ejercicios: { type: 'array', items: { type: 'object' }, nullable: true },
            diasSemana: { type: 'object', nullable: true },
            frecuenciaSemanal: { type: 'integer', minimum: 1, maximum: 7, nullable: true },
            duracionSemanas: { type: 'integer', minimum: 1, maximum: 52, nullable: true },
            observaciones: { type: 'string', nullable: true },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            ejerciciosAgregados: { type: 'array', items: { type: 'object' }, nullable: true },
            ejerciciosEliminados: { type: 'array', items: { type: 'object' }, nullable: true },
            modificacionCargas: { type: 'object', nullable: true },
          },
          required: ['accion'],
          example: {
            accion: 'modificada',
            comentario: 'Ajusté series y cargas por lesión de rodilla',
            observaciones: 'Variante sin impacto articular',
          },
        },
        HITLValidacionEjercicioResponse: {
          type: 'object',
          properties: {
            valido: { type: 'boolean' },
            razon: { type: 'string', nullable: true },
            contraindicaciones: { type: 'array', items: { type: 'string' } },
            nivelRiesgo: { type: 'string', enum: ['bajo', 'medio', 'alto'], nullable: true },
          },
          example: {
            valido: true,
            razon: 'Ejercicio seguro para el perfil del cliente',
            contraindicaciones: [],
            nivelRiesgo: 'bajo',
          },
        },
        HITLSugerenciaDietaRequest: {
          type: 'object',
          properties: {
            preferencias: {
              type: 'object',
              properties: {
                proposito: { type: 'string', enum: ['perder_peso', 'ganar_musculo', 'mantener'] },
              },
            },
          },
          example: {
            preferencias: {
              proposito: 'ganar_musculo',
            },
          },
        },
        HITLSugerenciaDietaResponse: {
          type: 'object',
          description: 'Respuesta del servicio de IA (Flask) con claves en camelCase.',
          properties: {
            success: { type: 'boolean' },
            objetivoCalorico: { type: 'integer' },
            proteinasGramos: { type: 'number' },
            carbohidratosGramos: { type: 'number' },
            grasasGramos: { type: 'number' },
            justificacion: { type: 'string', nullable: true },
            guardian: {
              type: 'object',
              properties: {
                aprobado: { type: 'boolean' },
                alertas: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      tipo: { type: 'string' },
                      nivelRiesgo: { type: 'string' },
                      mensaje: { type: 'string' },
                    },
                  },
                },
              },
            },
            sinLesiones: { type: 'boolean', nullable: true },
            advertenciaPerfilMedico: { type: 'boolean', nullable: true },
            metadata: { type: 'object', description: 'Metadatos del modelo (tiempoMs, versionModelo, motor)' },
          },
          example: {
            success: true,
            objetivoCalorico: 2400,
            proteinasGramos: 160,
            carbohidratosGramos: 280,
            grasasGramos: 80,
            justificacion: 'Plan de ganancia muscular para hombre de 28 años, nivel activo',
            guardian: { aprobado: true, alertas: [] },
            sinLesiones: true,
            advertenciaPerfilMedico: false,
            metadata: { tiempoMs: 210, versionModelo: '1.1.0', motor: 'reglas+nutricion' },
          },
        },
        HITLFeedbackRequest: {
          type: 'object',
          required: ['clienteId', 'accion'],
          properties: {
            clienteId: { type: 'integer' },
            rutinaSugeridaId: { type: 'integer', nullable: true },
            accion: { type: 'string', enum: ['aprobada', 'rechazada', 'modificada'] },
            rutinaOriginal: { type: 'object', nullable: true },
            rutinaFinal: { type: 'object', nullable: true },
            ejerciciosAgregados: { type: 'array', items: { type: 'object' } },
            ejerciciosEliminados: { type: 'array', items: { type: 'object' } },
            modificacionCargas: { type: 'array', items: { type: 'object' } },
            confianzaIa: { type: 'number', minimum: 0, maximum: 1 },
            tiempoRevisionSeg: { type: 'integer', minimum: 0 },
            observaciones: { type: 'string', maxLength: 2000 },
            tipo: { type: 'string', enum: ['rutina', 'dieta'], default: 'rutina' },
          },
          example: {
            clienteId: 2,
            rutinaSugeridaId: 5,
            accion: 'aprobada',
            observaciones: 'Rutina bien balanceada, aprobada sin cambios',
            tipo: 'rutina',
          },
        },
        HITLFeedbackResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            rutinaSugeridaId: { type: 'integer', nullable: true },
            entrenadorId: { type: 'integer' },
            clienteId: { type: 'integer' },
            accion: { type: 'string', enum: ['aprobada', 'rechazada', 'modificada'] },
            rutinaOriginal: { type: 'object', nullable: true },
            rutinaFinal: { type: 'object', nullable: true },
            ejerciciosAgregados: { type: 'array', items: { type: 'object' }, nullable: true },
            ejerciciosEliminados: { type: 'array', items: { type: 'object' }, nullable: true },
            modificacionCargas: { type: 'array', items: { type: 'object' }, nullable: true },
            confianzaIa: { type: 'number', nullable: true },
            tiempoRevisionSeg: { type: 'integer', nullable: true },
            observaciones: { type: 'string', nullable: true },
            tipo: { type: 'string', enum: ['rutina', 'dieta'] },
            createdAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            rutinaSugeridaId: 5,
            entrenadorId: 1,
            clienteId: 2,
            accion: 'aprobada',
            rutinaOriginal: null,
            rutinaFinal: null,
            ejerciciosAgregados: null,
            ejerciciosEliminados: null,
            modificacionCargas: null,
            confianzaIa: 0.87,
            tiempoRevisionSeg: 120,
            observaciones: 'Rutina bien balanceada',
            tipo: 'rutina',
            createdAt: '2025-07-10T14:30:00.000Z',
          },
        },
        DietaResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            objetivoCalorico: { type: 'integer', nullable: true },
            proteinas: { type: 'number', nullable: true },
            carbohidratos: { type: 'number', nullable: true },
            grasas: { type: 'number', nullable: true },
            observaciones: { type: 'string', nullable: true },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            activo: { type: 'boolean' },
            decision: { type: 'string', enum: ['pendiente', 'aprobada', 'rechazada', 'modificada'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            instruidoId: 2,
            entrenadorId: 1,
            objetivoCalorico: 2200,
            proteinas: 140,
            carbohidratos: 250,
            grasas: 75,
            observaciones: 'Plan de mantenimiento con enfoque en proteína',
            fechaInicio: '2025-07-01',
            fechaFin: '2025-07-31',
            activo: true,
            decision: 'aprobada',
          },
        },
        DietaCreateRequest: {
          type: 'object',
          required: ['instruidoId', 'objetivoCalorico'],
          properties: {
            instruidoId: { type: 'integer' },
            objetivoCalorico: { type: 'integer', minimum: 800, maximum: 8000 },
            proteinas: { type: 'number', minimum: 0, maximum: 500 },
            carbohidratos: { type: 'number', minimum: 0, maximum: 800 },
            grasas: { type: 'number', minimum: 0, maximum: 300 },
            observaciones: { type: 'string', maxLength: 2000 },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            activo: { type: 'boolean' },
          },
          example: {
            instruidoId: 2,
            objetivoCalorico: 2200,
            proteinas: 140,
            carbohidratos: 250,
            grasas: 75,
            observaciones: 'Plan de mantenimiento',
            fechaInicio: '2025-07-01',
            fechaFin: '2025-07-31',
          },
        },
        DietaGenerarRequest: {
          type: 'object',
          properties: {
            proposito: { type: 'string', enum: ['perder_peso', 'ganar_musculo', 'mantener'], default: 'mantener' },
          },
          example: {
            proposito: 'ganar_musculo',
          },
        },
        DietaGenerarResponse: {
          type: 'object',
          properties: {
            dieta: { $ref: '#/components/schemas/DietaResponse' },
            guardian: {
              type: 'object',
              properties: {
                aprobado: { type: 'boolean' },
                alertas: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      tipo: { type: 'string' },
                      nivelRiesgo: { type: 'string' },
                      mensaje: { type: 'string' },
                    },
                  },
                },
              },
            },
            justificacion: { type: 'string', nullable: true },
          },
          example: {
            dieta: {
              id: 2,
              instruidoId: 2,
              entrenadorId: 1,
              objetivoCalorico: 2800,
              proteinas: 180,
              carbohidratos: 320,
              grasas: 90,
              observaciones: null,
              fechaInicio: '2025-07-10',
              fechaFin: null,
              activo: false,
              decision: 'pendiente',
              createdAt: '2025-07-10T15:00:00.000Z',
              updatedAt: '2025-07-10T15:00:00.000Z',
            },
            guardian: { aprobado: true, alertas: [] },
            justificacion: 'Calculated for male, 28y, active level, muscle gain purpose',
          },
        },
        DietaDecisionRequest: {
          type: 'object',
          required: ['accion'],
          properties: {
            accion: { type: 'string', enum: ['aceptada', 'modificada', 'rechazada'] },
            comentario: { type: 'string', maxLength: 2000 },
            objetivoCalorico: { type: 'integer', minimum: 800, maximum: 8000 },
            proteinas: { type: 'number', minimum: 0, maximum: 500 },
            carbohidratos: { type: 'number', minimum: 0, maximum: 800 },
            grasas: { type: 'number', minimum: 0, maximum: 300 },
            observaciones: { type: 'string', maxLength: 2000 },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
          },
          example: {
            accion: 'aceptada',
            comentario: 'Dieta bien calculada, la apruebo',
          },
        },
        PlanPagoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            descripcion: { type: 'string', nullable: true },
            ofrecimiento: { type: 'string', enum: ['entrenamiento', 'dietas', 'ambos'] },
            montoUsd: { type: 'number' },
            diasVigencia: { type: 'integer' },
            activo: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            nombre: 'Plan Mensual Premium',
            descripcion: 'Acceso completo a entrenamiento y dietas',
            ofrecimiento: 'ambos',
            montoUsd: 30.00,
            diasVigencia: 30,
            activo: true,
          },
        },
        PlanPagoCreateRequest: {
          type: 'object',
          required: ['nombre', 'ofrecimiento', 'montoUsd'],
          properties: {
            nombre: { type: 'string', minLength: 2, maxLength: 150 },
            descripcion: { type: 'string', maxLength: 2000 },
            ofrecimiento: { type: 'string', enum: ['entrenamiento', 'dietas', 'ambos'] },
            montoUsd: { type: 'number', exclusiveMinimum: 0 },
            diasVigencia: { type: 'integer', minimum: 1, maximum: 365, default: 30 },
            activo: { type: 'boolean', default: true },
          },
          example: {
            nombre: 'Plan Mensual Básico',
            descripcion: 'Solo entrenamiento',
            ofrecimiento: 'entrenamiento',
            montoUsd: 20.00,
            diasVigencia: 30,
          },
        },
        MetodoPagoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            tipo: { type: 'string', enum: ['pago_movil', 'transferencia', 'zelle', 'binance', 'otro'] },
            datos: { type: 'object', description: 'Datos de contacto según método' },
            activo: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            tipo: 'pago_movil',
            datos: { banco: '0102', telefono: '04141234567', cedula: 'V-12345678' },
            activo: true,
          },
        },
        MetodoPagoCreateRequest: {
          type: 'object',
          required: ['tipo', 'datos'],
          properties: {
            tipo: { type: 'string', enum: ['pago_movil', 'transferencia', 'zelle', 'binance', 'otro'] },
            datos: { type: 'object', minProperties: 1, description: 'Datos según tipo: banco/telefono/cedula para pago_movil; banco/cuenta/titular para transferencia; correo para zelle; id para binance' },
            activo: { type: 'boolean', default: true },
          },
          example: {
            tipo: 'pago_movil',
            datos: { banco: '0102', telefono: '04141234567', cedula: 'V-12345678' },
          },
        },
        ConfiguracionPagoResponse: {
          type: 'object',
          properties: {
            entrenadorId: { type: 'integer' },
            tasaCambio: { type: 'number', description: 'Tasa de cambio USD -> Bs' },
          },
          example: {
            entrenadorId: 1,
            tasaCambio: 46.25,
          },
        },
        PagoResponse: {
          type: 'object',
          description: 'Objeto Pago sin el campo comprobante (nunca se expone en JSON). En listados incluye plan, metodo e Instruido.',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            planId: { type: 'integer' },
            metodoPagoId: { type: 'integer' },
            montoUsd: { type: 'number' },
            montoBs: { type: 'number' },
            tasaAplicada: { type: 'number' },
            referencia: { type: 'string' },
            fechaPago: { type: 'string', format: 'date' },
            estado: { type: 'string', enum: ['pendiente', 'verificado', 'rechazado'] },
            comentarioRechazo: { type: 'string', nullable: true },
            verificadoPor: { type: 'integer', nullable: true },
            fechaVerificacion: { type: 'string', format: 'date-time', nullable: true },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            errorPrediccionIa: { type: 'string', nullable: true, description: 'Error al disparar las sugerencias de IA tras verificar el pago (no afecta la respuesta)' },
            plan: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                nombre: { type: 'string' },
                montoUsd: { type: 'number' },
                diasVigencia: { type: 'integer' },
              },
            },
            metodo: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                tipo: { type: 'string' },
              },
            },
            Instruido: {
              type: 'object',
              nullable: true,
              description: 'Incluido solo en GET /api/pagos/historial',
              properties: {
                id: { type: 'integer' },
                nombre: { type: 'string' },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            instruidoId: 2,
            entrenadorId: 1,
            planId: 1,
            metodoPagoId: 1,
            montoUsd: 30.00,
            montoBs: 1387.50,
            tasaAplicada: 46.25,
            referencia: 'Pago-001234',
            fechaPago: '2025-07-10',
            estado: 'pendiente',
            comentarioRechazo: null,
            verificadoPor: null,
            fechaVerificacion: null,
            fechaInicio: null,
            fechaFin: null,
            errorPrediccionIa: null,
            plan: { id: 1, nombre: 'Plan Mensual Premium', montoUsd: 30.00, diasVigencia: 30 },
            metodo: { id: 1, tipo: 'pago_movil' },
            Instruido: { id: 2, nombre: 'Ana Martínez' },
            createdAt: '2025-07-10T12:00:00.000Z',
            updatedAt: '2025-07-10T12:00:00.000Z',
          },
        },
        PagoCatalogoResponse: {
          type: 'object',
          properties: {
            planes: { type: 'array', items: { $ref: '#/components/schemas/PlanPagoResponse' } },
            metodos: { type: 'array', items: { $ref: '#/components/schemas/MetodoPagoResponse' } },
            tasaCambio: { type: 'number' },
          },
          example: {
            planes: [
              { id: 1, nombre: 'Plan Mensual Premium', montoUsd: 30.00, diasVigencia: 30, ofrecimiento: 'ambos' },
            ],
            metodos: [
              { id: 1, tipo: 'pago_movil', datos: { banco: '0102', telefono: '04141234567' } },
            ],
            tasaCambio: 46.25,
          },
        },
        PagoRegistrarRequest: {
          type: 'object',
          required: ['planId', 'metodoPagoId', 'referencia', 'fechaPago', 'comprobante', 'comprobanteMime'],
          properties: {
            planId: { type: 'integer' },
            metodoPagoId: { type: 'integer' },
            referencia: { type: 'string', minLength: 3, maxLength: 100 },
            fechaPago: { type: 'string', format: 'date' },
            comprobante: { type: 'string', format: 'byte', description: 'Imagen del comprobante en base64' },
            comprobanteMime: { type: 'string', enum: ['image/jpeg', 'image/png', 'image/webp'] },
          },
          example: {
            planId: 1,
            metodoPagoId: 1,
            referencia: 'Pago-001234',
            fechaPago: '2025-07-10',
            comprobante: 'data:image/jpeg;base64,/9j/4AAQSkZJRg...',
            comprobanteMime: 'image/jpeg',
          },
        },
        SuscripcionResponse: {
          type: 'object',
          description: 'Tres variantes posibles: (1) suscripción vigente con fechas y días restantes; (2) sin suscripciones registradas ({activa:false, vencida:false, mensaje}); (3) suscripción vencida ({activa:false, vencida:true, fechaInicio, fechaFin, mensaje}).',
          properties: {
            activa: { type: 'boolean' },
            vencida: { type: 'boolean' },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            diasRestantes: { type: 'integer', nullable: true },
            plan: { type: 'string', nullable: true, description: 'Nombre del plan de la suscripción vigente' },
            mensaje: { type: 'string', nullable: true, description: 'Solo cuando no hay suscripción o está vencida' },
          },
          example: {
            activa: true,
            vencida: false,
            fechaInicio: '2025-07-01',
            fechaFin: '2025-07-31',
            diasRestantes: 21,
            plan: 'Plan Mensual Premium',
            mensaje: null,
          },
        },
        PagoRechazarRequest: {
          type: 'object',
          properties: {
            comentario: { type: 'string', maxLength: 255 },
          },
          example: {
            comentario: 'Comprobante ilegible, por favor enviar nuevamente',
          },
        },
        GrupoMuscularMetrica: {
          type: 'object',
          properties: {
            grupoMuscular: { type: 'string' },
            volumenTotal: { type: 'number' },
            pesoMaximoLevantado: { type: 'number' },
            totalSeries: { type: 'integer' },
            sesionesEntrenadas: { type: 'integer' },
          },
          example: {
            grupoMuscular: 'Pecho',
            volumenTotal: 12500,
            pesoMaximoLevantado: 80,
            totalSeries: 24,
            sesionesEntrenadas: 6,
          },
        },
        EvolucionSemanalItem: {
          type: 'object',
          properties: {
            semana: { type: 'string', example: '2026-W35' },
            grupoMuscular: { type: 'string' },
            volumenTotal: { type: 'number' },
            pesoMaximoLevantado: { type: 'number' },
            totalSeries: { type: 'integer' },
            sesionesEntrenadas: { type: 'integer' },
          },
          example: {
            semana: '2026-W35',
            grupoMuscular: 'Pecho',
            volumenTotal: 4200,
            pesoMaximoLevantado: 75,
            totalSeries: 8,
            sesionesEntrenadas: 2,
          },
        },
        ReporteGruposResponse: {
          type: 'object',
          properties: {
            instruidoId: { type: 'integer' },
            nombre: { type: 'string' },
            periodo: { type: 'string' },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            grupos: {
              type: 'array',
              items: { $ref: '#/components/schemas/GrupoMuscularMetrica' },
            },
            evolucionSemanal: {
              type: 'array',
              items: { $ref: '#/components/schemas/EvolucionSemanalItem' },
            },
          },
          example: {
            instruidoId: 2,
            nombre: 'María García',
            periodo: '30d',
            fechaInicio: '2026-08-05',
            fechaFin: '2026-09-04',
            grupos: [
              {
                grupoMuscular: 'Pecho',
                volumenTotal: 12500,
                pesoMaximoLevantado: 80,
                totalSeries: 24,
                sesionesEntrenadas: 6,
              },
            ],
            evolucionSemanal: [
              {
                semana: '2026-W35',
                grupoMuscular: 'Pecho',
                volumenTotal: 4200,
                pesoMaximoLevantado: 75,
                totalSeries: 8,
                sesionesEntrenadas: 2,
              },
            ],
          },
        },
        ReporteEvolucionResponse: {
          type: 'object',
          properties: {
            instruidoId: { type: 'integer' },
            nombre: { type: 'string' },
            grupoMuscular: { type: 'string' },
            periodo: { type: 'string' },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            evolucion: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  semana: { type: 'string' },
                  volumenTotal: { type: 'number' },
                  pesoMaximoLevantado: { type: 'number' },
                  totalSeries: { type: 'integer' },
                  sesionesEntrenadas: { type: 'integer' },
                },
              },
            },
          },
          example: {
            instruidoId: 2,
            nombre: 'María García',
            grupoMuscular: 'Pecho',
            periodo: '30d',
            fechaInicio: '2026-08-05',
            fechaFin: '2026-09-04',
            evolucion: [
              {
                semana: '2026-W35',
                volumenTotal: 4200,
                pesoMaximoLevantado: 75,
                totalSeries: 8,
                sesionesEntrenadas: 2,
              },
            ],
          },
        },
        ReporteComparativaResponse: {
          type: 'object',
          properties: {
            instruidoId: { type: 'integer' },
            nombre: { type: 'string' },
            periodo: { type: 'string' },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            volumenTotalPeriodo: { type: 'number' },
            volumenPromedioSemanalPeriodo: { type: 'number' },
            promedioHistoricoGlobal: {
              type: 'object',
              properties: {
                volumenPromedioSemanal: { type: 'number' },
                pesoMaximo: { type: 'number' },
                sesionesPromedioSemanal: { type: 'number' },
              },
            },
            comparativaOtros: {
              type: 'object',
              properties: {
                volumenPromedioSemanal: { type: 'number' },
              },
            },
          },
          example: {
            instruidoId: 2,
            nombre: 'María García',
            periodo: '30d',
            fechaInicio: '2026-08-05',
            fechaFin: '2026-09-04',
            volumenTotalPeriodo: 45000,
            volumenPromedioSemanalPeriodo: 11250,
            promedioHistoricoGlobal: {
              volumenPromedioSemanal: 9800,
              pesoMaximo: 90,
              sesionesPromedioSemanal: 3.5,
            },
            comparativaOtros: {
              volumenPromedioSemanal: 8500,
            },
          },
        },
        InstruidoResumenReporte: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            email: { type: 'string', format: 'email' },
            edad: { type: 'integer' },
            peso: { type: 'number' },
            altura: { type: 'number' },
            sexo: { type: 'string' },
            nivelActividad: { type: 'string' },
            fechaRegistro: { type: 'string', format: 'date' },
            activo: { type: 'boolean' },
            entrenadorId: { type: 'integer' },
          },
          example: {
            id: 2,
            nombre: 'María García',
            email: 'maria@example.com',
            edad: 28,
            peso: 65.5,
            altura: 1.65,
            sexo: 'femenino',
            nivelActividad: 'activo',
            fechaRegistro: '2025-03-10',
            activo: true,
            entrenadorId: 1,
          },
        },
        DashboardAdminResponse: {
          type: 'object',
          properties: {
            totalClientes: { type: 'integer' },
            totalEntrenadores: { type: 'integer' },
            rutinasActivas: { type: 'integer' },
            dietasActivas: { type: 'integer' },
            metabolicos: { type: 'integer' },
            clientesNuevosMes: { type: 'integer' },
          },
          example: {
            totalClientes: 45,
            totalEntrenadores: 5,
            rutinasActivas: 38,
            dietasActivas: 22,
            metabolicos: 30,
            clientesNuevosMes: 8,
          },
        },
        DashboardEntrenadorResponse: {
          type: 'object',
          properties: {
            totalClientes: { type: 'integer' },
            rutinasActivas: { type: 'integer' },
            dietasActivas: { type: 'integer' },
            clientesNuevosMes: { type: 'integer' },
            clientesRecientes: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'integer' },
                  nombre: { type: 'string' },
                  peso: { type: 'number' },
                  nivelActividad: { type: 'string' },
                  fechaRegistro: { type: 'string', format: 'date' },
                },
              },
            },
          },
          example: {
            totalClientes: 12,
            rutinasActivas: 10,
            dietasActivas: 6,
            clientesNuevosMes: 3,
            clientesRecientes: [
              { id: 2, nombre: 'Ana Martínez', peso: 58, nivelActividad: 'activo', fechaRegistro: '2025-06-15' },
              { id: 6, nombre: 'Pedro López', peso: 82, nivelActividad: 'moderado', fechaRegistro: '2025-07-01' },
            ],
          },
        },
        DashboardInstruidoResponse: {
          type: 'object',
          properties: {
            medicion: {
              type: 'object',
              nullable: true,
              properties: {
                peso: { type: 'number' },
                imc: { type: 'number' },
                fecha: { type: 'string', format: 'date' },
              },
            },
            rutinaActiva: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                nombre: { type: 'string' },
                tipo: { type: 'string' },
                fecha_inicio: { type: 'string', format: 'date' },
                fecha_fin: { type: 'string', format: 'date' },
                frecuencia_semanal: { type: 'integer' },
                observaciones: { type: 'string' },
              },
            },
            dietaActiva: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                objetivo_calorico: { type: 'integer' },
                proteinas_gramos: { type: 'number' },
                carbohidratos_gramos: { type: 'number' },
                grasas_gramos: { type: 'number' },
                fecha_inicio: { type: 'string', format: 'date' },
                fecha_fin: { type: 'string', format: 'date' },
              },
            },
            registrosRecientes: {
              type: 'array',
              items: { type: 'object' },
            },
          },
          example: {
            medicion: { peso: 65.5, imc: 24.1, fecha: '2025-07-01' },
            rutinaActiva: { id: 1, nombre: 'Full Body Fuerza', tipo: 'fuerza', fecha_inicio: '2025-07-01', fecha_fin: '2025-08-12', frecuencia_semanal: 3, observaciones: null },
            dietaActiva: { id: 1, objetivo_calorico: 2200, proteinas_gramos: 140, carbohidratos_gramos: 250, grasas_gramos: 75, fecha_inicio: '2025-07-01', fecha_fin: '2025-07-31' },
            registrosRecientes: [
              { id: 1, fecha: '2025-07-10', percepcion_esfuerzo: 7, duracion_minutos: 55, rutina_nombre: 'Full Body Fuerza' },
            ],
          },
        },
        PerfilMedicoResponse: {
          type: 'object',
          properties: {
            instruidoId: { type: 'integer' },
            alergias: { type: 'string', nullable: true, description: 'Datos medicos descifrados. Excepcion de seguridad autorizada: propio instruido, entrenador asignado o administrador.' },
            intolerancias: { type: 'string', nullable: true, description: 'Datos medicos descifrados. Excepcion de seguridad autorizada: propio instruido, entrenador asignado o administrador.' },
            lesiones: { type: 'string', nullable: true, description: 'Datos medicos descifrados. Excepcion de seguridad autorizada: propio instruido, entrenador asignado o administrador.' },
            condicionesPreexistentes: { type: 'string', nullable: true, description: 'Datos medicos descifrados. Excepcion de seguridad autorizada: propio instruido, entrenador asignado o administrador.' },
            medicacionActual: { type: 'string', nullable: true, description: 'Datos medicos descifrados. Excepcion de seguridad autorizada: propio instruido, entrenador asignado o administrador.' },
            observaciones: { type: 'string', nullable: true },
            perfilMedicoCompleto: { type: 'boolean' },
            datosMedicosCorruptos: { type: 'boolean', description: 'True si alguno de los campos sensibles no pudo descifrarse (p. ej. clave cambiada)' },
          },
          example: {
            instruidoId: 2,
            alergias: '["Gluten"]',
            intolerancias: '["Lactosa"]',
            lesiones: '["Esguince tobillo derecho 2023"]',
            condicionesPreexistentes: '[]',
            medicacionActual: 'Ninguna',
            observaciones: 'Paciente sana, sin restricciones mayores',
            perfilMedicoCompleto: true,
            datosMedicosCorruptos: false,
          },
        },
        PerfilMedicoRequest: {
          type: 'object',
          properties: {
            alergias: { type: 'string', description: 'JSON string con lista de alergias' },
            intolerancias: { type: 'string', description: 'JSON string con lista de intolerancias' },
            lesiones: { type: 'string', description: 'JSON string con lista de lesiones' },
            condicionesPreexistentes: { type: 'string', description: 'JSON string con condiciones preexistentes' },
            medicacionActual: { type: 'string' },
            observaciones: { type: 'string' },
          },
          example: {
            alergias: '["Mariscos"]',
            intolerancias: '[]',
            lesiones: '["Tendinitis hombro izquierdo"]',
            condicionesPreexistentes: '["Hipertensión controlada"]',
            medicacionActual: 'Losartán 50mg diario',
            observaciones: 'Controlar presión arterial durante entrenamiento intenso',
          },
        },
        MetabolismoCalculoRequest: {
          type: 'object',
          required: ['peso', 'altura', 'edad', 'sexo', 'nivelActividad'],
          properties: {
            peso: { type: 'number', minimum: 20, maximum: 400 },
            altura: { type: 'number', minimum: 0.5, maximum: 2.6 },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            clienteId: { type: 'integer', description: 'Obligatorio si el rol es entrenador/administrador' },
          },
          example: {
            peso: 75,
            altura: 1.78,
            edad: 28,
            sexo: 'masculino',
            nivelActividad: 'activo',
            clienteId: 2,
          },
        },
        MetabolismoResultadoResponse: {
          type: 'object',
          description: 'Si se envía clienteId, el cálculo se persiste en el histórico (calculos_metabolicos) pero no se devuelve en la respuesta.',
          properties: {
            tmb: { type: 'integer', description: 'Tasa Metabólica Basal (kcal/día), redondeada' },
            gct: { type: 'integer', description: 'Gasto Calórico Total (kcal/día), redondeado' },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
          },
          example: {
            tmb: 1750,
            gct: 3014,
            nivelActividad: 'activo',
          },
        },
        InstruidoCreateRequest: {
          type: 'object',
          required: ['nombre', 'edad', 'peso', 'altura', 'sexo', 'nivelActividad', 'diasDisponibles', 'diasSemana'],
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100, nullable: true },
            contrasena: { type: 'string', minLength: 8, maxLength: 100, nullable: true },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            peso: { type: 'number', exclusiveMinimum: 0 },
            altura: { type: 'number', exclusiveMinimum: 0 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            nivelExperiencia: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            propositoEntrenamiento: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'], nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7 },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minItems: 1, maxItems: 7 },
          },
          description: 'diasDisponibles debe coincidir con la cantidad de elementos de diasSemana.',
          example: {
            nombre: 'Pedro López',
            email: 'pedro@example.com',
            contrasena: 'MiClaveSegura1',
            edad: 30,
            peso: 82.0,
            altura: 1.80,
            sexo: 'masculino',
            nivelActividad: 'activo',
            nivelExperiencia: 'principiante',
            propositoEntrenamiento: 'perdida_peso',
            diasDisponibles: 3,
            diasSemana: [1, 3, 5],
          },
        },
        InstruidoUpdateRequest: {
          type: 'object',
          description: 'Actualización de un instruido por parte de entrenador/administrador. Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100 },
            contrasena: { type: 'string', minLength: 8, maxLength: 100 },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            peso: { type: 'number', exclusiveMinimum: 0 },
            altura: { type: 'number', exclusiveMinimum: 0 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            nivelExperiencia: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            propositoEntrenamiento: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'], nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7 },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minItems: 1, maxItems: 7 },
            activo: { type: 'boolean' },
          },
          example: {
            peso: 80.5,
            nivelActividad: 'muy_activo',
            activo: true,
          },
        },
        InstruidoUpdatePropioRequest: {
          type: 'object',
          description: 'Actualización del perfil propio del instruido. Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100 },
            contrasena: { type: 'string', minLength: 8, maxLength: 100 },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            peso: { type: 'number', exclusiveMinimum: 0 },
            altura: { type: 'number', exclusiveMinimum: 0 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            nivelExperiencia: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            propositoEntrenamiento: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'], nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7 },
            diasSemana: { type: 'array', items: { type: 'integer', minimum: 1, maximum: 7 }, minItems: 1, maxItems: 7 },
          },
          example: {
            peso: 64.0,
            altura: 1.65,
            propositoEntrenamiento: 'perdida_peso',
          },
        },
        DietaUpdateRequest: {
          type: 'object',
          description: 'Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            objetivoCalorico: { type: 'integer', minimum: 800, maximum: 8000 },
            proteinas: { type: 'number', minimum: 0, maximum: 500 },
            carbohidratos: { type: 'number', minimum: 0, maximum: 800 },
            grasas: { type: 'number', minimum: 0, maximum: 300 },
            observaciones: { type: 'string', maxLength: 2000, nullable: true },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            activo: { type: 'boolean' },
          },
          example: {
            objetivoCalorico: 2400,
            proteinas: 150,
          },
        },
        PlanPagoUpdateRequest: {
          type: 'object',
          description: 'Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            nombre: { type: 'string', minLength: 2, maxLength: 150 },
            descripcion: { type: 'string', maxLength: 2000, nullable: true },
            ofrecimiento: { type: 'string', enum: ['entrenamiento', 'dietas', 'ambos'] },
            montoUsd: { type: 'number', exclusiveMinimum: 0, maximum: 99999999 },
            diasVigencia: { type: 'integer', minimum: 1, maximum: 365 },
            activo: { type: 'boolean' },
          },
          example: {
            montoUsd: 25.00,
            activo: true,
          },
        },
        MetodoPagoUpdateRequest: {
          type: 'object',
          description: 'Todos los campos son opcionales; debe enviarse al menos uno.',
          properties: {
            tipo: { type: 'string', enum: ['pago_movil', 'transferencia', 'zelle', 'binance', 'otro'] },
            datos: { type: 'object', minProperties: 1, description: 'Datos según tipo: banco/telefono/cedula para pago_movil; banco/cuenta/titular para transferencia; correo para zelle; id para binance' },
            activo: { type: 'boolean' },
          },
          example: {
            activo: false,
          },
        },
        TasaCambioRequest: {
          type: 'object',
          required: ['tasaCambio'],
          properties: {
            tasaCambio: { type: 'number', exclusiveMinimum: 0, maximum: 999999.9999, description: 'Tasa de cambio USD -> Bs (4 decimales)' },
          },
          example: {
            tasaCambio: 46.25,
          },
        },
      },
    },
    tags: [
      { name: 'Auth', description: 'Autenticación y gestión de usuarios' },
      { name: 'Health', description: 'Verificación de estado del servicio' },
      { name: 'Instruidos', description: 'Gestión de clientes (instruidos) y perfiles médicos' },
      { name: 'Metabolismo', description: 'Cálculo de tasa metabólica (TMB/GCT)' },
      { name: 'Ejercicios', description: 'Catálogo de ejercicios' },
      { name: 'Plantillas', description: 'Plantillas de entrenamiento del entrenador' },
      { name: 'Rutinas Asignadas', description: 'Rutinas asignadas a instruidos' },
      { name: 'Registro Entrenamiento', description: 'Registro y seguimiento de sesiones de entrenamiento' },
      { name: 'HITL', description: 'Motor de IA con validación Guardian y feedback del entrenador' },
      { name: 'Dietas', description: 'Planes de dieta' },
      { name: 'Pagos', description: 'Planes de mensualidad, métodos de pago, tasa de cambio y verificación de pagos' },
      { name: 'Reportes', description: 'Métricas, evolución y comparativas de entrenamiento por grupo muscular' },
      { name: 'Dashboard', description: 'Estadísticas por rol' },
    ],
  },
  apis: [
    './src/app.js',
    './src/modules/auth/auth.routes.js',
    './src/modules/instruidos/instruido.routes.js',
    './src/modules/instruidos/perfil-medico.routes.js',
    './src/modules/metabolismo/metabolismo.routes.js',
    './src/modules/entrenamiento/entrenamiento.routes.js',
    './src/modules/entrenamiento/ejercicios.routes.js',
    './src/modules/entrenamiento/plantillas.routes.js',
    './src/modules/entrenamiento/rutinas-asignadas.routes.js',
    './src/modules/entrenamiento/registro-entrenamiento.routes.js',
    './src/modules/entrenamiento/hitl.routes.js',
    './src/modules/dietas/dietas.routes.js',
    './src/modules/pagos/pagos.routes.js',
    './src/modules/reportes/reportes.routes.js',
    './src/modules/dashboard/dashboard.routes.js',
  ],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
