const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Sistema de Información - API',
      version: '1.0.0',
      description: 'API del sistema de información para entrenamiento físico. Gestiona autenticación, perfiles, metabolismo, entrenamientos, dietas, pagos y reportes.',
    },
    servers: [
      { url: 'http://localhost:3000', description: 'Servidor de desarrollo' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Ingresa tu token JWT de acceso en el formato: Bearer <token>',
        },
      },
      responses: {
        Error: {
          description: 'Error controlado por la API',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
            },
          },
        },
      },
      schemas: {
        ErrorResponse: {
          type: 'object',
          properties: {
            error: { type: 'string', description: 'Mensaje descriptivo del error' },
          },
          example: { error: 'Mensaje de error descriptivo' },
        },
        AuthSuccessResponse: {
          type: 'object',
          properties: {
            accessToken: { type: 'string', description: 'JWT de acceso (15 min de validez)' },
            refreshToken: { type: 'string', description: 'JWT de actualización (10 días de validez)' },
            user: {
              type: 'object',
              properties: {
                id: { type: 'integer', description: 'ID del usuario' },
                nombre: { type: 'string', description: 'Nombre completo' },
                email: { type: 'string', format: 'email', description: 'Correo electrónico' },
                rol: { type: 'string', enum: ['administrador', 'entrenador', 'instruido'], description: 'Rol del usuario' },
                tipo: { type: 'string', enum: ['entrenador', 'instruido'], description: 'Tipo de cuenta' },
                especialidad: { type: 'string', nullable: true, description: 'Especialidad (solo entrenadores/administradores)' },
              },
            },
          },
          example: {
            accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            user: {
              id: 1,
              nombre: 'Juan Pérez',
              email: 'juan@example.com',
              rol: 'entrenador',
              tipo: 'entrenador',
              especialidad: 'Nutrición deportiva',
            },
          },
        },
        TokenPairResponse: {
          type: 'object',
          properties: {
            accessToken: { type: 'string', description: 'Nuevo JWT de acceso' },
            refreshToken: { type: 'string', description: 'Nuevo JWT de actualización' },
          },
          example: {
            accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
          },
        },
        LogoutResponse: {
          type: 'object',
          properties: {
            message: { type: 'string', description: 'Mensaje de confirmación' },
          },
          example: { message: 'Sesión cerrada correctamente' },
        },
        UserEntrenador: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            email: { type: 'string', format: 'email' },
            especialidad: { type: 'string', nullable: true },
            rol: { type: 'string', enum: ['administrador', 'entrenador'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            nombre: 'Carlos López',
            email: 'carlos@example.com',
            especialidad: 'Entrenamiento funcional',
            rol: 'entrenador',
            createdAt: '2025-01-15T10:30:00.000Z',
            updatedAt: '2025-06-20T14:22:00.000Z',
          },
        },
        UserInstruido: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            email: { type: 'string', format: 'email' },
            edad: { type: 'integer' },
            peso: { type: 'number', format: 'decimal' },
            altura: { type: 'number', format: 'decimal' },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            propositoEntrenamiento: { type: 'string', nullable: true },
            diasDisponibles: { type: 'integer', nullable: true },
            fechaRegistro: { type: 'string', format: 'date' },
            activo: { type: 'boolean' },
            entrenadorId: { type: 'integer', nullable: true },
            rol: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 2,
            nombre: 'María García',
            email: 'maria@example.com',
            edad: 28,
            peso: 65.50,
            altura: 1.65,
            sexo: 'femenino',
            nivelActividad: 'activo',
            propositoEntrenamiento: 'Perder peso y tonificar',
            diasDisponibles: 4,
            fechaRegistro: '2025-03-10',
            activo: true,
            entrenadorId: 1,
            rol: 'instruido',
            createdAt: '2025-03-10T09:00:00.000Z',
            updatedAt: '2025-07-01T16:45:00.000Z',
          },
        },
        RegisterRequest: {
          type: 'object',
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100 },
            contrasena: { type: 'string', minLength: 8, maxLength: 100, description: 'Contraseña del usuario' },
            especialidad: { type: 'string', maxLength: 100, nullable: true },
            rol: { type: 'string', enum: ['administrador', 'entrenador', 'instruido'], default: 'instruido' },
            edad: { type: 'integer', minimum: 1, maximum: 120, description: 'Requerido si rol=instruido' },
            peso: { type: 'number', exclusiveMinimum: 0, description: 'Requerido si rol=instruido' },
            altura: { type: 'number', exclusiveMinimum: 0, description: 'Requerido si rol=instruido' },
            sexo: { type: 'string', enum: ['masculino', 'femenino'], description: 'Requerido si rol=instruido' },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'], description: 'Requerido si rol=instruido' },
            entrenadorId: { type: 'integer', nullable: true },
          },
          example: {
            nombre: 'Nuevo Usuario',
            email: 'nuevo@example.com',
            contrasena: 'Password123',
            rol: 'entrenador',
            especialidad: 'Yoga y meditación',
          },
        },
        RegisterInstruidoRequest: {
          type: 'object',
          required: ['nombre', 'email', 'contrasena', 'edad', 'peso', 'altura', 'sexo', 'nivelActividad'],
          properties: {
            nombre: { type: 'string', maxLength: 100 },
            email: { type: 'string', format: 'email', maxLength: 100 },
            contrasena: { type: 'string', minLength: 8, maxLength: 100 },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            peso: { type: 'number', exclusiveMinimum: 0 },
            altura: { type: 'number', exclusiveMinimum: 0 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            propositoEntrenamiento: { type: 'string', nullable: true },
            diasDisponibles: { type: 'integer', minimum: 1, maximum: 7, nullable: true },
          },
          example: {
            nombre: 'Ana Martínez',
            email: 'ana@example.com',
            contrasena: 'MiClaveSegura1',
            edad: 25,
            peso: 58.0,
            altura: 1.62,
            sexo: 'femenino',
            nivelActividad: 'moderado',
            propositoEntrenamiento: 'Mejorar condición física general',
            diasDisponibles: 3,
          },
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'contrasena'],
          properties: {
            email: { type: 'string', format: 'email' },
            contrasena: { type: 'string', description: 'Contraseña del usuario' },
          },
          example: {
            email: 'usuario@example.com',
            contrasena: 'MiPassword123',
          },
        },
        RefreshRequest: {
          type: 'object',
          required: ['refreshToken'],
          properties: {
            refreshToken: { type: 'string', description: 'JWT de actualización' },
          },
          example: {
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
          },
        },
        UpdateProfileRequest: {
          type: 'object',
          properties: {
            nombre: { type: 'string', maxLength: 100, nullable: true },
            email: { type: 'string', format: 'email', maxLength: 100, nullable: true },
            especialidad: { type: 'string', maxLength: 100, nullable: true, description: 'Solo para entrenadores' },
            contrasena: { type: 'string', minLength: 8, maxLength: 100, nullable: true, description: 'Nueva contraseña' },
            contrasenaActual: { type: 'string', description: 'Obligatorio si se proporciona contrasena' },
          },
          example: {
            nombre: 'Nombre Actualizado',
            especialidad: 'Nueva especialidad',
          },
        },
        HealthResponse: {
          type: 'object',
          properties: {
            status: { type: 'string' },
            service: { type: 'string' },
          },
          example: { status: 'ok', service: 'backend-node' },
        },
        Certificacion: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            institucion: { type: 'string', nullable: true },
            fechaObtencion: { type: 'string', format: 'date', nullable: true },
            fechaExpiracion: { type: 'string', format: 'date', nullable: true },
            descripcion: { type: 'string', nullable: true },
            imagenUrl: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            nombre: 'CrossFit Level 2 Trainer',
            institucion: 'CrossFit Inc.',
            fechaObtencion: '2024-01-15',
            fechaExpiracion: '2026-01-15',
            descripcion: 'Certificación avanzada en entrenamiento funcional',
            imagenUrl: 'https://ejemplo.com/cert-crossfit-l2.jpg',
          },
        },
        CertificacionRequest: {
          type: 'object',
          required: ['nombre'],
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            institucion: { type: 'string', maxLength: 150, nullable: true },
            fechaObtencion: { type: 'string', format: 'date', nullable: true },
            fechaExpiracion: { type: 'string', format: 'date', nullable: true },
            descripcion: { type: 'string', nullable: true },
            imagenUrl: { type: 'string', format: 'uri', nullable: true },
          },
          example: {
            nombre: 'Certificación en Nutrición Deportiva',
            institucion: 'Universidad Nacional',
            fechaObtencion: '2023-06-01',
            fechaExpiracion: '2028-06-01',
            descripcion: 'Especialización en nutrición para deportistas',
            imagenUrl: 'https://ejemplo.com/cert-nutricion.jpg',
          },
        },
        EjercicioResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nombre: { type: 'string' },
            descripcion: { type: 'string', nullable: true },
            instruccionesEs: { type: 'string', nullable: true },
            grupoMuscular: { type: 'string', nullable: true },
            target: { type: 'string', nullable: true },
            equipoNecesario: { type: 'string', nullable: true },
            dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            musculosSecundarios: { type: 'array', items: { type: 'string' }, nullable: true },
            contraindicaLesiones: { type: 'string', nullable: true },
            imagenUrl: { type: 'string', nullable: true },
            gifUrl: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            nombre: 'Sentadilla con barra',
            descripcion: 'Ejercicio compuesto para tren inferior',
            instruccionesEs: 'Colocar la barra sobre trapecios, bajar hasta parallelo y subir.',
            grupoMuscular: 'Cuádriceps',
            target: 'Piernas',
            equipoNecesario: 'Barra, rack',
            dificultad: 'intermedio',
            musculosSecundarios: ['Glúteos', 'Isquiotibiales'],
            contraindicaLesiones: 'Rodilla, espalda baja',
            imagenUrl: 'https://ejemplo.com/sentadilla.jpg',
            gifUrl: 'https://ejemplo.com/sentadilla.gif',
          },
        },
        EjercicioListResponse: {
          type: 'object',
          properties: {
            total: { type: 'integer' },
            pagina: { type: 'integer' },
            limite: { type: 'integer' },
            datos: { type: 'array', items: { $ref: '#/components/schemas/EjercicioResponse' } },
          },
          example: {
            total: 150,
            pagina: 1,
            limite: 20,
            datos: [
              { id: 1, nombre: 'Sentadilla con barra', grupoMuscular: 'Cuádriceps', dificultad: 'intermedio' },
              { id: 2, nombre: 'Press de banca', grupoMuscular: 'Pecho', dificultad: 'intermedio' },
            ],
          },
        },
        EjercicioCreateRequest: {
          type: 'object',
          required: ['nombre'],
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string' },
            instruccionesEs: { type: 'string' },
            grupoMuscular: { type: 'string', maxLength: 50 },
            target: { type: 'string', maxLength: 100 },
            equipoNecesario: { type: 'string', maxLength: 100 },
            dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
            musculosSecundarios: { type: 'array', items: { type: 'string' } },
            contraindicaLesiones: { type: 'string' },
            imagenUrl: { type: 'string' },
            gifUrl: { type: 'string' },
          },
          example: {
            nombre: 'Remo con mancuerna',
            descripcion: 'Ejercicio unilateral para espalda',
            grupoMuscular: 'Espalda',
            target: 'Dorsal',
            equipoNecesario: 'Mancuerna',
            dificultad: 'principiante',
          },
        },
        EjercicioUpdateRequest: {
          type: 'object',
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string' },
            instruccionesEs: { type: 'string' },
            grupoMuscular: { type: 'string', maxLength: 50 },
            target: { type: 'string', maxLength: 100 },
            equipoNecesario: { type: 'string', maxLength: 100 },
            dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
            musculosSecundarios: { type: 'array', items: { type: 'string' } },
            contraindicaLesiones: { type: 'string' },
            imagenUrl: { type: 'string' },
            gifUrl: { type: 'string' },
          },
          example: {
            nombre: 'Sentadilla con barra (actualizado)',
            dificultad: 'avanzado',
          },
        },
        EjercicioRutinaItem: {
          type: 'object',
          properties: {
            ejercicio_id: { type: 'integer', description: 'ID del ejercicio del catálogo' },
            dia: { type: 'integer', minimum: 1, maximum: 7, description: 'Día de la semana (1-7)' },
            orden: { type: 'integer', minimum: 1, description: 'Orden dentro del día' },
            series: { type: 'integer', minimum: 1, maximum: 20 },
            repeticiones: { type: 'integer', minimum: 1, maximum: 100 },
            carga_kg: { type: 'number', minimum: 0, nullable: true },
            descanso_segundos: { type: 'integer', minimum: 0, maximum: 600 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            ejercicio_id: 1,
            dia: 1,
            orden: 1,
            series: 4,
            repeticiones: 8,
            carga_kg: 60,
            descanso_segundos: 90,
            notas: 'Controlar la bajada',
          },
        },
        PlantillaResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            descripcion: { type: 'string', nullable: true },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
            diasSemana: { type: 'object', description: 'Mapa de días de la semana' },
            frecuenciaSemanal: { type: 'integer' },
            duracionSemanas: { type: 'integer', nullable: true },
            objetivo: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'], nullable: true },
            nivelDificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'], nullable: true },
            activa: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            nombre: 'Full Body Fuerza',
            descripcion: 'Rutina de fuerza tren completo 3 días',
            tipo: 'fuerza',
            ejercicios: [
              { ejercicio_id: 1, dia: 1, orden: 1, series: 4, repeticiones: 8, carga_kg: 60 },
              { ejercicio_id: 5, dia: 1, orden: 2, series: 3, repeticiones: 10, carga_kg: 30 },
            ],
            diasSemana: { '1': { dia_semana: 1, nombre: 'Lunes' }, '3': { dia_semana: 3, nombre: 'Miércoles' }, '5': { dia_semana: 5, nombre: 'Viernes' } },
            frecuenciaSemanal: 3,
            duracionSemanas: 8,
            objetivo: 'ganancia_muscular',
            nivelDificultad: 'intermedio',
            activa: true,
          },
        },
        PlantillaCreateRequest: {
          type: 'object',
          required: ['nombre', 'tipo', 'ejercicios', 'dias_semana', 'frecuencia_semanal'],
          properties: {
            nombre: { type: 'string', maxLength: 150 },
            descripcion: { type: 'string' },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' }, minItems: 1 },
            dias_semana: { type: 'object', description: 'Mapa { "1": { dia_semana: 1, nombre: "Lunes" } }' },
            frecuencia_semanal: { type: 'integer', minimum: 1, maximum: 7 },
            duracion_semanas: { type: 'integer', minimum: 1, maximum: 52 },
            objetivo: { type: 'string', enum: ['perdida_peso', 'ganancia_muscular', 'mantenimiento', 'rendimiento', 'rehabilitacion'] },
            nivel_dificultad: { type: 'string', enum: ['principiante', 'intermedio', 'avanzado'] },
          },
          example: {
            nombre: 'Push Pull Legs',
            tipo: 'hipertrofia',
            ejercicios: [
              { ejercicio_id: 2, dia: 1, orden: 1, series: 4, repeticiones: 10, carga_kg: 40 },
              { ejercicio_id: 7, dia: 1, orden: 2, series: 3, repeticiones: 12, carga_kg: 15 },
            ],
            dias_semana: { '1': { dia_semana: 1, nombre: 'Lunes' }, '3': { dia_semana: 3, nombre: 'Miércoles' }, '5': { dia_semana: 5, nombre: 'Viernes' } },
            frecuencia_semanal: 3,
            duracion_semanas: 12,
            objetivo: 'ganancia_muscular',
            nivel_dificultad: 'intermedio',
          },
        },
        PlantillaDiaResponse: {
          type: 'object',
          properties: {
            plantillaId: { type: 'integer' },
            dia: { type: 'integer' },
            nombre: { type: 'string' },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
          },
          example: {
            plantillaId: 1,
            dia: 1,
            nombre: 'Lunes',
            ejercicios: [
              { ejercicio_id: 1, dia: 1, orden: 1, series: 4, repeticiones: 8, carga_kg: 60 },
              { ejercicio_id: 5, dia: 1, orden: 2, series: 3, repeticiones: 10, carga_kg: 30 },
            ],
          },
        },
        RutinaAsignadaResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            plantillaOrigenId: { type: 'integer', nullable: true },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
            diasSemana: { type: 'object' },
            frecuenciaSemanal: { type: 'integer' },
            duracionSemanas: { type: 'integer', nullable: true },
            observaciones: { type: 'string', nullable: true },
            personalizadaPorEntrenador: { type: 'boolean' },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            activa: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            instruidoId: 2,
            plantillaOrigenId: 1,
            entrenadorId: 1,
            nombre: 'IA - Full Body Fuerza',
            tipo: 'fuerza',
            ejercicios: [
              { ejercicio_id: 1, dia: 1, orden: 1, series: 4, repeticiones: 8, carga_kg: 50 },
            ],
            diasSemana: { '1': { dia_semana: 1, nombre: 'Lunes' }, '3': { dia_semana: 3, nombre: 'Miércoles' } },
            frecuenciaSemanal: 2,
            duracionSemanas: 6,
            observaciones: '{"confianza":0.85,"explicacion":"Basado en nivel intermedio"}',
            personalizadaPorEntrenador: false,
            fechaInicio: '2025-07-01',
            fechaFin: '2025-08-12',
            activa: true,
          },
        },
        RutinaCreateRequest: {
          type: 'object',
          required: ['cliente_id', 'nombre', 'tipo', 'ejercicios', 'dias_semana', 'frecuencia_semanal'],
          properties: {
            cliente_id: { type: 'integer' },
            plantilla_origen_id: { type: 'integer', nullable: true },
            nombre: { type: 'string', maxLength: 150 },
            tipo: { type: 'string', enum: ['fuerza', 'hipertrofia', 'resistencia', 'cardio', 'funcional', 'flexibilidad'] },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' }, minItems: 1 },
            dias_semana: { type: 'object' },
            frecuencia_semanal: { type: 'integer', minimum: 1, maximum: 7 },
            duracion_semanas: { type: 'integer', minimum: 1, maximum: 52 },
            observaciones: { type: 'string' },
            fecha_inicio: { type: 'string', format: 'date' },
            fecha_fin: { type: 'string', format: 'date' },
          },
          example: {
            cliente_id: 2,
            nombre: 'Rutina Personal Ana',
            tipo: 'hipertrofia',
            ejercicios: [
              { ejercicio_id: 1, dia: 1, orden: 1, series: 4, repeticiones: 10, carga_kg: 40 },
            ],
            dias_semana: { '1': { dia_semana: 1, nombre: 'Lunes' }, '4': { dia_semana: 4, nombre: 'Jueves' } },
            frecuencia_semanal: 2,
            duracion_semanas: 8,
            fecha_inicio: '2025-07-01',
          },
        },
        RutinaClonarRequest: {
          type: 'object',
          required: ['instruido_id'],
          properties: {
            instruido_id: { type: 'integer' },
            fecha_inicio: { type: 'string', format: 'date' },
            observaciones: { type: 'string' },
          },
          example: {
            instruido_id: 6,
            fecha_inicio: '2025-07-15',
            observaciones: 'Clonada desde plantilla para nuevo cliente',
          },
        },
        RutinaDiaResponse: {
          type: 'object',
          properties: {
            rutinaId: { type: 'integer' },
            dia: { type: 'integer' },
            nombre: { type: 'string' },
            ejercicios: { type: 'array', items: { $ref: '#/components/schemas/EjercicioRutinaItem' } },
          },
          example: {
            rutinaId: 1,
            dia: 1,
            nombre: 'Lunes',
            ejercicios: [
              { ejercicio_id: 1, dia: 1, orden: 1, series: 4, repeticiones: 8, carga_kg: 50 },
            ],
          },
        },
        RutinaResumenResponse: {
          type: 'object',
          properties: {
            rutinaId: { type: 'integer' },
            nombre: { type: 'string' },
            tipo: { type: 'string' },
            frecuenciaSemanal: { type: 'integer' },
            duracionSemanas: { type: 'integer', nullable: true },
            totalEjercicios: { type: 'integer' },
            diasConEjercicios: { type: 'integer' },
            resumenPorDia: { type: 'array', items: { type: 'object' } },
          },
          example: {
            rutinaId: 1,
            nombre: 'Full Body Fuerza',
            tipo: 'fuerza',
            frecuenciaSemanal: 3,
            duracionSemanas: 8,
            totalEjercicios: 12,
            diasConEjercicios: 3,
            resumenPorDia: [
              { dia: 1, nombre: 'Lunes', ejercicios: 4 },
              { dia: 3, nombre: 'Miércoles', ejercicios: 4 },
              { dia: 5, nombre: 'Viernes', ejercicios: 4 },
            ],
          },
        },
        RegistroEntrenamientoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            rutinaAsignadaId: { type: 'integer' },
            instruidoId: { type: 'integer' },
            fecha: { type: 'string', format: 'date' },
            ejerciciosRealizados: { type: 'array', items: { type: 'object' }, nullable: true },
            duracionMinutos: { type: 'integer', nullable: true },
            percepcionEsfuerzo: { type: 'integer', minimum: 1, maximum: 10, nullable: true },
            observaciones: { type: 'string', nullable: true },
            estado: { type: 'string', enum: ['en_progreso', 'completado', 'cancelado'] },
            fechaInicio: { type: 'string', format: 'date-time' },
            fechaFin: { type: 'string', format: 'date-time', nullable: true },
          },
          example: {
            id: 1,
            rutinaAsignadaId: 1,
            instruidoId: 2,
            fecha: '2025-07-10',
            ejerciciosRealizados: [
              { ejercicio_id: 1, nombre: 'Sentadilla', series_completadas: 4 },
            ],
            duracionMinutos: 55,
            percepcionEsfuerzo: 7,
            observaciones: 'Buena sesión',
            estado: 'completado',
            fechaInicio: '2025-07-10T08:00:00.000Z',
            fechaFin: '2025-07-10T08:55:00.000Z',
          },
        },
        RegistroCrearRequest: {
          type: 'object',
          required: ['rutinaAsignadaId'],
          properties: {
            rutinaAsignadaId: { type: 'integer' },
            instruidoId: { type: 'integer' },
            fecha: { type: 'string', format: 'date' },
            ejerciciosRealizados: { type: 'array', items: { type: 'object' } },
            percepcionEsfuerzo: { type: 'integer', minimum: 1, maximum: 10 },
            duracionMinutos: { type: 'integer', minimum: 0, maximum: 600 },
            observaciones: { type: 'string', maxLength: 2000 },
          },
          example: {
            rutinaAsignadaId: 1,
            fecha: '2025-07-10',
            percepcionEsfuerzo: 7,
            duracionMinutos: 55,
            observaciones: 'Buena sesión de fuerza',
          },
        },
        RegistroIniciarRequest: {
          type: 'object',
          required: ['rutinaAsignadaId'],
          properties: {
            rutinaAsignadaId: { type: 'integer' },
            instruidoId: { type: 'integer' },
            observaciones: { type: 'string', maxLength: 2000 },
          },
          example: {
            rutinaAsignadaId: 1,
            observaciones: 'Inicio de sesión de entrenamiento',
          },
        },
        SerieResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            registroEntrenamientoId: { type: 'integer' },
            ejercicioId: { type: 'integer' },
            numeroSerie: { type: 'integer' },
            repeticionesRealizadas: { type: 'integer' },
            pesoKg: { type: 'number' },
            descansoSegundos: { type: 'integer' },
            rpe: { type: 'integer', minimum: 1, maximum: 10, nullable: true },
            notas: { type: 'string', nullable: true },
          },
          example: {
            id: 1,
            registroEntrenamientoId: 1,
            ejercicioId: 1,
            numeroSerie: 1,
            repeticionesRealizadas: 8,
            pesoKg: 60,
            descansoSegundos: 90,
            rpe: 7,
            notas: null,
          },
        },
        SerieCreateRequest: {
          type: 'object',
          required: ['ejercicioId', 'numeroSerie', 'repeticionesRealizadas', 'pesoKg', 'descansoSegundos'],
          properties: {
            ejercicioId: { type: 'integer' },
            numeroSerie: { type: 'integer', minimum: 1 },
            repeticionesRealizadas: { type: 'integer', minimum: 0 },
            pesoKg: { type: 'number', minimum: 0 },
            descansoSegundos: { type: 'integer', minimum: 0 },
            rpe: { type: 'integer', minimum: 1, maximum: 10 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            ejercicioId: 1,
            numeroSerie: 1,
            repeticionesRealizadas: 8,
            pesoKg: 60,
            descansoSegundos: 90,
            rpe: 7,
          },
        },
        SerieUpdateRequest: {
          type: 'object',
          properties: {
            ejercicioId: { type: 'integer' },
            numeroSerie: { type: 'integer', minimum: 1 },
            repeticionesRealizadas: { type: 'integer', minimum: 0 },
            pesoKg: { type: 'number', minimum: 0 },
            descansoSegundos: { type: 'integer', minimum: 0 },
            rpe: { type: 'integer', minimum: 1, maximum: 10 },
            notas: { type: 'string', maxLength: 500 },
          },
          example: {
            repeticionesRealizadas: 10,
            pesoKg: 62.5,
          },
        },
        HITLSugerenciaRutinaRequest: {
          type: 'object',
          properties: {
            preferencias: {
              type: 'object',
              properties: {
                excluir: { type: 'array', items: { type: 'string' }, description: 'IDs o nombres de ejercicios a excluir' },
                equipamiento: { type: 'array', items: { type: 'string' }, description: 'Equipamiento disponible' },
              },
            },
          },
          example: {
            preferencias: {
              excluir: ['Sentadilla con barra'],
              equipamiento: ['Mancuernas', 'Barra', 'Banco'],
            },
          },
        },
        HITLSugerenciaRutinaResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            plantilla_id: { type: 'integer', nullable: true, description: 'ID de la plantilla sugerida por la IA' },
            confianza: { type: 'number', minimum: 0, maximum: 1, description: 'Nivel de confianza del modelo (0-1)' },
            explicacion: { type: 'string', nullable: true, description: 'Justificación de la recomendación' },
            advertencia: { type: 'string', nullable: true, description: 'Advertencia de seguridad si aplica' },
            hasLesiones: { type: 'boolean', description: 'Si el cliente tiene lesiones registradas' },
            lesionesDetalle: { type: 'array', items: { type: 'string' }, description: 'Detalle de lesiones del cliente' },
            metadata: { type: 'object', description: 'Metadatos adicionales del modelo' },
          },
          example: {
            success: true,
            plantilla_id: 3,
            confianza: 0.87,
            explicacion: 'Se recomienda rutina de hipertrofia moderada dado nivel intermedio y disponibilidad de 4 días.',
            advertencia: null,
            hasLesiones: true,
            lesionesDetalle: ['Hernia discal L4-L5'],
            metadata: { modelo: 'recommender_v2', tiempo_ms: 320 },
          },
        },
        HITLValidacionEjercicioResponse: {
          type: 'object',
          properties: {
            valido: { type: 'boolean' },
            razon: { type: 'string', nullable: true },
            contraindicaciones: { type: 'array', items: { type: 'string' } },
            nivel_riesgo: { type: 'string', enum: ['bajo', 'medio', 'alto'], nullable: true },
          },
          example: {
            valido: true,
            razon: 'Ejercicio seguro para el perfil del cliente',
            contraindicaciones: [],
            nivel_riesgo: 'bajo',
          },
        },
        HITLSugerenciaDietaRequest: {
          type: 'object',
          properties: {
            preferencias: {
              type: 'object',
              properties: {
                proposito: { type: 'string', enum: ['perder_peso', 'ganar_musculo', 'mantener'] },
              },
            },
          },
          example: {
            preferencias: {
              proposito: 'ganar_musculo',
            },
          },
        },
        HITLSugerenciaDietaResponse: {
          type: 'object',
          properties: {
            objetivo_calorico: { type: 'integer' },
            proteinas_gramos: { type: 'number' },
            carbohidratos_gramos: { type: 'number' },
            grasas_gramos: { type: 'number' },
            justificacion: { type: 'string', nullable: true },
            guardian: {
              type: 'object',
              properties: {
                aprobado: { type: 'boolean' },
                advertencias: { type: 'array', items: { type: 'string' } },
              },
            },
          },
          example: {
            objetivo_calorico: 2400,
            proteinas_gramos: 160,
            carbohidratos_gramos: 280,
            grasas_gramos: 80,
            justificacion: 'Plan de ganancia muscular para hombre de 28 años, nivel activo',
            guardian: { aprobado: true, advertencias: [] },
          },
        },
        HITLFeedbackRequest: {
          type: 'object',
          required: ['clienteId', 'accion'],
          properties: {
            clienteId: { type: 'integer' },
            rutinaSugeridaId: { type: 'integer', nullable: true },
            accion: { type: 'string', enum: ['aprobada', 'rechazada', 'modificada'] },
            rutinaOriginal: { type: 'object', nullable: true },
            rutinaFinal: { type: 'object', nullable: true },
            ejerciciosAgregados: { type: 'array', items: { type: 'object' } },
            ejerciciosEliminados: { type: 'array', items: { type: 'object' } },
            modificacionCargas: { type: 'array', items: { type: 'object' } },
            confianzaIa: { type: 'number', minimum: 0, maximum: 1 },
            tiempoRevisionSeg: { type: 'integer', minimum: 0 },
            observaciones: { type: 'string', maxLength: 2000 },
            tipo: { type: 'string', enum: ['rutina', 'dieta'], default: 'rutina' },
          },
          example: {
            clienteId: 2,
            rutinaSugeridaId: 5,
            accion: 'aprobada',
            observaciones: 'Rutina bien balanceada, aprobada sin cambios',
            tipo: 'rutina',
          },
        },
        HITLFeedbackResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            rutinaSugeridaId: { type: 'integer', nullable: true },
            entrenadorId: { type: 'integer' },
            clienteId: { type: 'integer' },
            accion: { type: 'string', enum: ['aprobada', 'rechazada', 'modificada'] },
            rutinaOriginal: { type: 'object', nullable: true },
            rutinaFinal: { type: 'object', nullable: true },
            ejerciciosAgregados: { type: 'array', items: { type: 'object' }, nullable: true },
            ejerciciosEliminados: { type: 'array', items: { type: 'object' }, nullable: true },
            modificacionCargas: { type: 'array', items: { type: 'object' }, nullable: true },
            confianzaIa: { type: 'number', nullable: true },
            tiempoRevisionSeg: { type: 'integer', nullable: true },
            observaciones: { type: 'string', nullable: true },
            tipo: { type: 'string', enum: ['rutina', 'dieta'] },
            created_at: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            rutinaSugeridaId: 5,
            entrenadorId: 1,
            clienteId: 2,
            accion: 'aprobada',
            rutinaOriginal: null,
            rutinaFinal: null,
            ejerciciosAgregados: null,
            ejerciciosEliminados: null,
            modificacionCargas: null,
            confianzaIa: 0.87,
            tiempoRevisionSeg: 120,
            observaciones: 'Rutina bien balanceada',
            tipo: 'rutina',
            created_at: '2025-07-10T14:30:00.000Z',
          },
        },
        DietaResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            objetivoCalorico: { type: 'integer', nullable: true },
            proteinas: { type: 'number', nullable: true },
            carbohidratos: { type: 'number', nullable: true },
            grasas: { type: 'number', nullable: true },
            observaciones: { type: 'string', nullable: true },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            activo: { type: 'boolean' },
            decision: { type: 'string', enum: ['pendiente', 'aprobada', 'rechazada', 'modificada'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            instruidoId: 2,
            entrenadorId: 1,
            objetivoCalorico: 2200,
            proteinas: 140,
            carbohidratos: 250,
            grasas: 75,
            observaciones: 'Plan de mantenimiento con enfoque en proteína',
            fechaInicio: '2025-07-01',
            fechaFin: '2025-07-31',
            activo: true,
            decision: 'aprobada',
          },
        },
        DietaCreateRequest: {
          type: 'object',
          required: ['instruidoId', 'objetivoCalorico'],
          properties: {
            instruidoId: { type: 'integer' },
            objetivoCalorico: { type: 'integer', minimum: 800, maximum: 8000 },
            proteinas: { type: 'number', minimum: 0, maximum: 500 },
            carbohidratos: { type: 'number', minimum: 0, maximum: 800 },
            grasas: { type: 'number', minimum: 0, maximum: 300 },
            observaciones: { type: 'string', maxLength: 2000 },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
            activo: { type: 'boolean' },
          },
          example: {
            instruidoId: 2,
            objetivoCalorico: 2200,
            proteinas: 140,
            carbohidratos: 250,
            grasas: 75,
            observaciones: 'Plan de mantenimiento',
            fechaInicio: '2025-07-01',
            fechaFin: '2025-07-31',
          },
        },
        DietaGenerarRequest: {
          type: 'object',
          properties: {
            proposito: { type: 'string', enum: ['perder_peso', 'ganar_musculo', 'mantener'], default: 'mantener' },
          },
          example: {
            proposito: 'ganar_musculo',
          },
        },
        DietaGenerarResponse: {
          type: 'object',
          properties: {
            dieta: { $ref: '#/components/schemas/DietaResponse' },
            guardian: {
              type: 'object',
              properties: {
                aprobado: { type: 'boolean' },
                advertencias: { type: 'array', items: { type: 'string' } },
              },
            },
            justificacion: { type: 'string', nullable: true },
          },
          example: {
            dieta: {
              id: 2,
              instruidoId: 2,
              entrenadorId: 1,
              objetivoCalorico: 2800,
              proteinas: 180,
              carbohidratos: 320,
              grasas: 90,
              observaciones: 'Plan de ganancia muscular calculado por IA',
              activo: false,
              decision: 'pendiente',
            },
            guardian: { aprobado: true, advertencias: [] },
            justificacion: 'Calculated for male, 28y, active level, muscle gain purpose',
          },
        },
        DietaDecisionRequest: {
          type: 'object',
          required: ['accion'],
          properties: {
            accion: { type: 'string', enum: ['aceptada', 'modificada', 'rechazada'] },
            comentario: { type: 'string', maxLength: 2000 },
            objetivoCalorico: { type: 'integer', minimum: 800, maximum: 8000 },
            proteinas: { type: 'number', minimum: 0, maximum: 500 },
            carbohidratos: { type: 'number', minimum: 0, maximum: 800 },
            grasas: { type: 'number', minimum: 0, maximum: 300 },
            observaciones: { type: 'string', maxLength: 2000 },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
          },
          example: {
            accion: 'aceptada',
            comentario: 'Dieta bien calculada, la apruebo',
          },
        },
        PlanPagoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            nombre: { type: 'string' },
            descripcion: { type: 'string', nullable: true },
            ofrecimiento: { type: 'string', enum: ['entrenamiento', 'dietas', 'ambos'] },
            montoUsd: { type: 'number' },
            diasVigencia: { type: 'integer' },
            activo: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            nombre: 'Plan Mensual Premium',
            descripcion: 'Acceso completo a entrenamiento y dietas',
            ofrecimiento: 'ambos',
            montoUsd: 30.00,
            diasVigencia: 30,
            activo: true,
          },
        },
        PlanPagoCreateRequest: {
          type: 'object',
          required: ['nombre', 'ofrecimiento', 'montoUsd'],
          properties: {
            nombre: { type: 'string', minLength: 2, maxLength: 150 },
            descripcion: { type: 'string', maxLength: 2000 },
            ofrecimiento: { type: 'string', enum: ['entrenamiento', 'dietas', 'ambos'] },
            montoUsd: { type: 'number', exclusiveMinimum: 0 },
            diasVigencia: { type: 'integer', minimum: 1, maximum: 365, default: 30 },
            activo: { type: 'boolean', default: true },
          },
          example: {
            nombre: 'Plan Mensual Básico',
            descripcion: 'Solo entrenamiento',
            ofrecimiento: 'entrenamiento',
            montoUsd: 20.00,
            diasVigencia: 30,
          },
        },
        MetodoPagoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            tipo: { type: 'string', enum: ['pago_movil', 'transferencia', 'zelle', 'binance', 'otro'] },
            datos: { type: 'object', description: 'Datos de contacto según método' },
            activo: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            entrenadorId: 1,
            tipo: 'pago_movil',
            datos: { banco: '0102', telefono: '04141234567', cedula: 'V-12345678' },
            activo: true,
          },
        },
        MetodoPagoCreateRequest: {
          type: 'object',
          required: ['tipo', 'datos'],
          properties: {
            tipo: { type: 'string', enum: ['pago_movil', 'transferencia', 'zelle', 'binance', 'otro'] },
            datos: { type: 'object', minProperties: 1, description: 'Datos según tipo: banco/telefono/cedula para pago_movil; banco/cuenta/titular para transferencia; correo para zelle; id para binance' },
            activo: { type: 'boolean', default: true },
          },
          example: {
            tipo: 'pago_movil',
            datos: { banco: '0102', telefono: '04141234567', cedula: 'V-12345678' },
          },
        },
        ConfiguracionPagoResponse: {
          type: 'object',
          properties: {
            entrenadorId: { type: 'integer' },
            tasaCambio: { type: 'number', description: 'Tasa de cambio USD -> Bs' },
          },
          example: {
            entrenadorId: 1,
            tasaCambio: 46.25,
          },
        },
        PagoResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            entrenadorId: { type: 'integer' },
            planId: { type: 'integer' },
            metodoPagoId: { type: 'integer' },
            montoUsd: { type: 'number' },
            montoBs: { type: 'number' },
            tasaAplicada: { type: 'number' },
            referencia: { type: 'string' },
            fechaPago: { type: 'string', format: 'date' },
            estado: { type: 'string', enum: ['pendiente', 'verificado', 'rechazado'] },
            comentarioRechazo: { type: 'string', nullable: true },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            id: 1,
            instruidoId: 2,
            entrenadorId: 1,
            planId: 1,
            metodoPagoId: 1,
            montoUsd: 30.00,
            montoBs: 1387.50,
            tasaAplicada: 46.25,
            referencia: 'Pago-001234',
            fechaPago: '2025-07-10',
            estado: 'pendiente',
            comentarioRechazo: null,
            fechaInicio: null,
            fechaFin: null,
          },
        },
        PagoCatalogoResponse: {
          type: 'object',
          properties: {
            planes: { type: 'array', items: { $ref: '#/components/schemas/PlanPagoResponse' } },
            metodos: { type: 'array', items: { $ref: '#/components/schemas/MetodoPagoResponse' } },
            tasaCambio: { type: 'number' },
          },
          example: {
            planes: [
              { id: 1, nombre: 'Plan Mensual Premium', montoUsd: 30.00, diasVigencia: 30, ofrecimiento: 'ambos' },
            ],
            metodos: [
              { id: 1, tipo: 'pago_movil', datos: { banco: '0102', telefono: '04141234567' } },
            ],
            tasaCambio: 46.25,
          },
        },
        PagoRegistrarRequest: {
          type: 'object',
          required: ['planId', 'metodoPagoId', 'referencia', 'fechaPago', 'comprobante', 'comprobanteMime'],
          properties: {
            planId: { type: 'integer' },
            metodoPagoId: { type: 'integer' },
            referencia: { type: 'string', minLength: 3, maxLength: 100 },
            fechaPago: { type: 'string', format: 'date' },
            comprobante: { type: 'string', format: 'byte', description: 'Imagen del comprobante en base64' },
            comprobanteMime: { type: 'string', enum: ['image/jpeg', 'image/png', 'image/webp'] },
          },
          example: {
            planId: 1,
            metodoPagoId: 1,
            referencia: 'Pago-001234',
            fechaPago: '2025-07-10',
            comprobante: 'data:image/jpeg;base64,/9j/4AAQSkZJRg...',
            comprobanteMime: 'image/jpeg',
          },
        },
        SuscripcionResponse: {
          type: 'object',
          properties: {
            activa: { type: 'boolean' },
            fechaInicio: { type: 'string', format: 'date', nullable: true },
            fechaFin: { type: 'string', format: 'date', nullable: true },
            diasRestantes: { type: 'integer', nullable: true },
            plan: { type: 'string', nullable: true },
          },
          example: {
            activa: true,
            fechaInicio: '2025-07-01',
            fechaFin: '2025-07-31',
            diasRestantes: 21,
            plan: 'Plan Mensual Premium',
          },
        },
        PagoVerificarResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            estado: { type: 'string', enum: ['verificado'] },
            fechaVerificacion: { type: 'string', format: 'date-time' },
            fechaInicio: { type: 'string', format: 'date' },
            fechaFin: { type: 'string', format: 'date' },
          },
          example: {
            id: 1,
            estado: 'verificado',
            fechaVerificacion: '2025-07-10T15:00:00.000Z',
            fechaInicio: '2025-07-10',
            fechaFin: '2025-08-09',
          },
        },
        PagoRechazarRequest: {
          type: 'object',
          properties: {
            comentario: { type: 'string', maxLength: 255 },
          },
          example: {
            comentario: 'Comprobante ilegible, por favor enviar nuevamente',
          },
        },
        RendimientoMensualResponse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            instruidoId: { type: 'integer' },
            fecha: { type: 'string', format: 'date' },
            peso: { type: 'number', nullable: true },
            repeticionesTotales: { type: 'integer', nullable: true },
            cargaTotalKg: { type: 'number', nullable: true },
            imc: { type: 'number', nullable: true },
            observaciones: { type: 'string', nullable: true },
          },
          example: {
            id: 1,
            instruidoId: 2,
            fecha: '2025-07-01',
            peso: 65.5,
            repeticionesTotales: 480,
            cargaTotalKg: 12500,
            imc: 24.1,
            observaciones: 'Buena progresión mensual',
          },
        },
        DashboardAdminResponse: {
          type: 'object',
          properties: {
            totalClientes: { type: 'integer' },
            totalEntrenadores: { type: 'integer' },
            rutinasActivas: { type: 'integer' },
            dietasActivas: { type: 'integer' },
            metabolicos: { type: 'integer' },
            clientesNuevosMes: { type: 'integer' },
          },
          example: {
            totalClientes: 45,
            totalEntrenadores: 5,
            rutinasActivas: 38,
            dietasActivas: 22,
            metabolicos: 30,
            clientesNuevosMes: 8,
          },
        },
        DashboardEntrenadorResponse: {
          type: 'object',
          properties: {
            totalClientes: { type: 'integer' },
            rutinasActivas: { type: 'integer' },
            dietasActivas: { type: 'integer' },
            clientesNuevosMes: { type: 'integer' },
            clientesRecientes: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'integer' },
                  nombre: { type: 'string' },
                  peso: { type: 'number' },
                  nivelActividad: { type: 'string' },
                  fechaRegistro: { type: 'string', format: 'date' },
                },
              },
            },
          },
          example: {
            totalClientes: 12,
            rutinasActivas: 10,
            dietasActivas: 6,
            clientesNuevosMes: 3,
            clientesRecientes: [
              { id: 2, nombre: 'Ana Martínez', peso: 58, nivelActividad: 'activo', fechaRegistro: '2025-06-15' },
              { id: 6, nombre: 'Pedro López', peso: 82, nivelActividad: 'moderado', fechaRegistro: '2025-07-01' },
            ],
          },
        },
        DashboardInstruidoResponse: {
          type: 'object',
          properties: {
            medicion: {
              type: 'object',
              nullable: true,
              properties: {
                peso: { type: 'number' },
                imc: { type: 'number' },
                fecha: { type: 'string', format: 'date' },
              },
            },
            rutinaActiva: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                nombre: { type: 'string' },
                tipo: { type: 'string' },
                fecha_inicio: { type: 'string', format: 'date' },
                fecha_fin: { type: 'string', format: 'date' },
                frecuencia_semanal: { type: 'integer' },
                observaciones: { type: 'string' },
              },
            },
            dietaActiva: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                objetivo_calorico: { type: 'integer' },
                proteinas_gramos: { type: 'number' },
                carbohidratos_gramos: { type: 'number' },
                grasas_gramos: { type: 'number' },
                fecha_inicio: { type: 'string', format: 'date' },
                fecha_fin: { type: 'string', format: 'date' },
              },
            },
            registrosRecientes: {
              type: 'array',
              items: { type: 'object' },
            },
          },
          example: {
            medicion: { peso: 65.5, imc: 24.1, fecha: '2025-07-01' },
            rutinaActiva: { id: 1, nombre: 'Full Body Fuerza', tipo: 'fuerza', fecha_inicio: '2025-07-01', fecha_fin: '2025-08-12', frecuencia_semanal: 3, observaciones: null },
            dietaActiva: { id: 1, objetivo_calorico: 2200, proteinas_gramos: 140, carbohidratos_gramos: 250, grasas_gramos: 75, fecha_inicio: '2025-07-01', fecha_fin: '2025-07-31' },
            registrosRecientes: [
              { id: 1, fecha: '2025-07-10', percepcion_esfuerzo: 7, duracion_minutos: 55, rutina_nombre: 'Full Body Fuerza' },
            ],
          },
        },
        PerfilMedicoResponse: {
          type: 'object',
          properties: {
            instruidoId: { type: 'integer' },
            alergias: { type: 'string', nullable: true, description: 'Campo cifrado con AES-256-CBC' },
            intolerancias: { type: 'string', nullable: true, description: 'Campo cifrado con AES-256-CBC' },
            lesiones: { type: 'string', nullable: true, description: 'Campo cifrado con AES-256-CBC' },
            condicionesPreexistentes: { type: 'string', nullable: true, description: 'Campo cifrado con AES-256-CBC' },
            medicacionActual: { type: 'string', nullable: true },
            observaciones: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
          example: {
            instruidoId: 2,
            alergias: '[\"Gluten\"]',
            intolerancias: '[\"Lactosa\"]',
            lesiones: '[\"Esguince tobillo derecho 2023\"]',
            condicionesPreexistentes: '[]',
            medicacionActual: 'Ninguna',
            observaciones: 'Paciente sana, sin restricciones mayores',
          },
        },
        PerfilMedicoRequest: {
          type: 'object',
          properties: {
            alergias: { type: 'string', description: 'JSON string con lista de alergias' },
            intolerancias: { type: 'string', description: 'JSON string con lista de intolerancias' },
            lesiones: { type: 'string', description: 'JSON string con lista de lesiones' },
            condicionesPreexistentes: { type: 'string', description: 'JSON string con condiciones preexistentes' },
            medicacionActual: { type: 'string' },
            observaciones: { type: 'string' },
          },
          example: {
            alergias: '["Mariscos"]',
            intolerancias: '[]',
            lesiones: '["Tendinitis hombro izquierdo"]',
            condicionesPreexistentes: '["Hipertensión controlada"]',
            medicacionActual: 'Losartán 50mg diario',
            observaciones: 'Controlar presión arterial durante entrenamiento intenso',
          },
        },
        MetabolismoCalculoRequest: {
          type: 'object',
          required: ['peso', 'altura', 'edad', 'sexo', 'nivelActividad'],
          properties: {
            peso: { type: 'number', minimum: 20, maximum: 400 },
            altura: { type: 'number', minimum: 0.5, maximum: 2.6 },
            edad: { type: 'integer', minimum: 1, maximum: 120 },
            sexo: { type: 'string', enum: ['masculino', 'femenino'] },
            nivelActividad: { type: 'string', enum: ['sedentario', 'ligero', 'moderado', 'activo', 'muy_activo'] },
            clienteId: { type: 'integer', description: 'Obligatorio si el rol es entrenador/administrador' },
          },
          example: {
            peso: 75,
            altura: 1.78,
            edad: 28,
            sexo: 'masculino',
            nivelActividad: 'activo',
            clienteId: 2,
          },
        },
        MetabolismoResultadoResponse: {
          type: 'object',
          properties: {
            clienteId: { type: 'integer' },
            tmb: { type: 'number', description: 'Tasa Metabólica Basal (kcal/día)' },
            gct: { type: 'number', description: 'Gasto Calórico Total (kcal/día)' },
            nivelActividadUsado: { type: 'string' },
            pesoUsado: { type: 'number' },
            fechaCalculo: { type: 'string', format: 'date-time' },
          },
          example: {
            clienteId: 2,
            tmb: 1750.50,
            gct: 2968.35,
            nivelActividadUsado: 'activo',
            pesoUsado: 75,
            fechaCalculo: '2025-07-10T10:30:00.000Z',
          },
        },
      },
    },
    tags: [
      { name: 'Auth', description: 'Autenticación y gestión de usuarios' },
      { name: 'Health', description: 'Verificación de estado del servicio' },
      { name: 'Instruidos', description: 'Gestión de clientes (instruidos) y perfiles médicos' },
      { name: 'Metabolismo', description: 'Cálculo de tasa metabólica (TMB/GCT)' },
      { name: 'Ejercicios', description: 'Catálogo de ejercicios' },
      { name: 'Plantillas', description: 'Plantillas de entrenamiento del entrenador' },
      { name: 'Rutinas Asignadas', description: 'Rutinas asignadas a instruidos' },
      { name: 'Registro Entrenamiento', description: 'Registro y seguimiento de sesiones de entrenamiento' },
      { name: 'HITL', description: 'Motor de IA con validación Guardian y feedback del entrenador' },
      { name: 'Dietas', description: 'Planes de dieta' },
      { name: 'Pagos', description: 'Planes de mensualidad, métodos de pago, tasa de cambio y verificación de pagos' },
      { name: 'Reportes', description: 'Rendimiento mensual de instruidos' },
      { name: 'Dashboard', description: 'Estadísticas por rol' },
    ],
  },
  apis: [
    './src/app.js',
    './src/modules/auth/auth.routes.js',
    './src/modules/instruidos/instruido.routes.js',
    './src/modules/instruidos/perfil-medico.routes.js',
    './src/modules/metabolismo/metabolismo.routes.js',
    './src/modules/entrenamiento/entrenamiento.routes.js',
    './src/modules/entrenamiento/ejercicios.routes.js',
    './src/modules/entrenamiento/plantillas.routes.js',
    './src/modules/entrenamiento/rutinas-asignadas.routes.js',
    './src/modules/entrenamiento/registro-entrenamiento.routes.js',
    './src/modules/entrenamiento/hitl.routes.js',
    './src/modules/dietas/dietas.routes.js',
    './src/modules/pagos/pagos.routes.js',
    './src/modules/reportes/reportes.routes.js',
    './src/modules/dashboard/dashboard.routes.js',
  ],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
